### ISSUE TITLE
lxc-destroy is really destructive

### ISSUE THREAD

**Issue by realitix** [lxc/lxc#1051]
Hello everyone,
I created a container under my home `/home/me/lxc/vm1` with `lxc-create --name vm1 -B dir --dir /home/me/lxc/vm1 --template ubuntu` .

Next I start a `lxc-destroy --name vm1`.

Then lxc launchs a recusrive rm and destroy everything in my home. lxc should only delete `/home/me/lxc/vm1` but now my home is empty and I lost a lot of work...

Can you take a look at this ? Is this the desired behavior ?

**Comment by hallyn** [comment]
Holy cow, that absolutely should not happen.  The rm will not
cross device boundaries, though that isn't needed to delete
the rest of the homedir.  What's needed is a symbolic link

Somehow in 8 years this hasn't really been a problem, but it's
severe enough that I think we can do something like do a pass
over the rootfs before delete to unlink any symbolic link.  I.e

find $rootfs -xdev -type l -exec "rm" "{}" \;

Note that in general,

1. rather than the 'ubuntu' template you probably want to use
the download template

2. since you used the ubuntu template, you must have run lxc-create
as root.  This means that the container config was under
/var/lib/lxc/v1/ while the rootfs, owned by root, was under your
homedir.

3. your container would have been running as root rather than
unprivileged.

The recommended way to run a container under your homedir would
be as non-root to do

lxc-create -t download -n v1 -- -d ubuntu -r xenial -a amd64

then destroy it as non-root with

lxc-destroy -n v1

then the homedir will be under ~/.local/share/lxc, the container
won't be privileged over the host or even (by default) your 'me'
userid.

(But of course there will be cases where that isn't what you want,
and what you did is...)

**Comment by js78** [comment]
Thanks @hallyn for your answer. Indeed I should not run lxc as root but I was testing the beast!
Do you want me to close this issue ?

**Comment by hallyn** [comment]
On Sun, Jun 19, 2016 at 11:39:10AM -0700, js78 wrote:
> Thanks @hallyn for your answer. Indeed I should not run lxc as root but I was testing the beast!
> Do you want me to close this issue ?

No, please do not close the issue.  I'd like us to figure out exactly how
this happened and how we can prevent it in the future.

Running as non-root is safer in several ways, however it's not always
wrong, and does not on its own explain this.

Can you tell us which distro/release you are on, and which where
you got the lxc package or how you built it?  I'd like to try to
reproduce it.

**Comment by js78** [comment]
Ubuntu version: 16.04
Lxc: 2.0.1-0ubuntu1~16.04.1

I tried to reproduce it but I can't... It just destroys the container.

**Comment by brauner** [comment]
I tried to reproduce it this weekend on
Ubuntu 16.04 LTS
LXC: 2.0.1

and could not reproduce. However, I didn't try anything fancy with symlinks as @hallyn suspected. So this should still be tested.

**Comment by realitix** [comment]
I close this issue. It's old now
