### ISSUE TITLE
"lsof -i" may not show all open/listening network ports

### ISSUE THREAD

**Issue by simos** [lxc/lxc#1059]
Tested with: Ubuntu 15.10/16.04, lxc 2.0.2.

If you install some network services in your LXC container, the open ports may not show when you run "lsof -i". You need to use the "ss" command instead (preinstalled, package "iproute2").

HOW TO REPRODUCE:
a. Set up

```
 $ lxc launch ubuntu:x c1
 $ lxc exec c1 -- /bin/bash
 # apt update   
 # apt upgrade
 # apt install postfix
 ### Select "Internet Site" from the list of different configurations, thus it binds to port 25 (smtp).
```

b. Verify that port 25 is listening

```
 root@c1:~# telnet c1.lxd smtp
 Trying 10.173.82.209...
 Connected to c1.lxd.
 Escape character is '^]'.
 220 c1.lxd ESMTP Postfix (Ubuntu)
 quit
 221 2.0.0 Bye
 Connection closed by foreign host.
 root@c1:~#
```

c. Run "lsof -i"

```
 root@c1:~# lsof -i
 COMMAND  PID USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
 dhclient 620 root    6u  IPv4  32673      0t0  UDP *:bootpc
 sshd     717 root    3u  IPv4  33706      0t0  TCP *:ssh (LISTEN)
 sshd     717 root    4u  IPv6  33708      0t0  TCP *:ssh (LISTEN)
 root@c1:~# 
```

Does not show any reference to port 25 (smtp) being open.
If should have shown something like the following, if ran outside of a container,

```
 master    14979            root   12u  IPv4 143124      0t0  TCP *:smtp (LISTEN)
 master    14979            root   13u  IPv6 143125      0t0  TCP *:smtp (LISTEN)
```

d. Run "ss -tula"

```
 root@c1:~# ss -tula
 Netid  State      Recv-Q Send-Q Local Address:Port                 Peer Address:Port                
 udp    UNCONN     0      0       *:bootpc                *:*                    
 tcp    LISTEN     0      100     *:smtp                  *:*                    
 tcp    LISTEN     0      128     *:ssh                   *:*                    
 tcp    LISTEN     0      100    :::smtp                 :::*                    
 tcp    LISTEN     0      128    :::ssh                  :::*                    
 root@c1:~#
```

It shows that port 25 (smtp) is indeed open.

**Comment by nehaljwani** [comment]
I think this happens because from inside the container lsof isn't able to read `/proc/${pid_of_postfix}/fd`  . The problem goes away when the container is launched in privileged mode: `lxc launch ubuntu:x c1  -c security.privileged=true`
Somewhat relevant: http://unix.stackexchange.com/q/136690/24475

**Comment by tssge** [comment]
I think a bug I filed a while back might be related: https://github.com/lxc/lxcfs/issues/89 It was closed however, as it was not lxcfs related.

**Comment by brauner** [comment]
This is not really a LX{C,D} bug but a kernel-enforced security restriction.

**Comment by clement-analogue** [comment]
Just encounter this behavior on a container launched with LXD. lsof -i4 does not show apache listening on port 80 and 443. This issue is close because it is not considered as bug. I don't question that. However, I think there should be somehow a warning when a software is not acting as expected and it is known behavior.
I struggled to attempt to solve a "non issue". Try to understand why things appears to not work, while they do but the investigation tools returns incomplete information without warning.
There should be a mechanism to warn the user about these, similar to when we try to launch a command which requires root privilege from a non-root user.

**Comment by simos** [comment]
This is mostly a bug within the utility (`lsof`) and the way it uses to retrieve information about open ports. 
The other utility, `ss`, uses some other way to find the open ports, and can show the proper results.

If `lsof` only uses one way to find the open ports, and is unable to add the way `ss` uses, then they most likely will not fix this. 
In any case, you can look in the bug reports for `lsof` whether they mention this issue, and if so, post the link here.
