### ISSUE TITLE
Nested lxd creation slow

### ISSUE THREAD

**Issue by hatched** [lxc/lxc#1115]
It seems that when creating an lxd inside another lxd it takes considerably longer than on the host.

Ubuntu 16.04.1
LXC 2.0.3

```Bash
# lxd was init'd with a zfs pool
$ time lxc launch ubuntu: test
Creating test
Starting test

real    0m4.495s
user    0m0.008s
sys     0m0.004s

$ lxc config set test security.nesting true
$ lxc config set test security.privileged true
$ lxc stop test
$ lxc start test
$ lxc exec test -- /bin/bash
# now inside the test lxd
$ lxc launch ubuntu: tester # So that it creates the cert & downloads the template
$ time lxc launch ubuntu: tester-nested
Creating tester-nested
Starting tester-nested

real    0m18.516s
user    0m0.008s
sys     0m0.004s
```

**Comment by stgraber** [comment]
My guess is that the host LXD uses zfs or btrfs for fast container creation but LXD inside the container doesn't, meaning it must unpack the 150MB image and write it to disk which takes time.

ZFS doesn't support delegation so you can't really nest with it, btrfs does but you need the btrfs tools installed in the container and a custom mount option set for your filesystem on the host.

**Comment by hatched** [comment]
I originally had the same idea however when creating the nested lxd the size of the pool increases by ~640MB so I had assumed it was still using the same pool for the child containers.

As an aside, in an attempt to `lxd init` with zfs in the 'test' lxd I get the following error:
```
error: Failed to create the ZFS pool: The /dev/zfs device is missing and must be created.
Try running 'udevadm trigger' as root to create it.
```
running `udevadm trigger` doesn't appear to do anything.

**Comment by stgraber** [comment]
You see the parent zfs volume grow simply because lxd in the container is writing data to disk, but as I said, zfs doesn't support delegation so the container cannot create the new zfs volumes needed by lxd and so simply uses the fallback directory backend which means unpacking tarballs for every container.

lxd init fails due to /dev/zfs being missing and there's no safe way for you to expose /dev/zfs to the container. Even if you did it in an unsafe way, since zfs isn't aware of containers, you'd see the host zfs filesystems rather than anything inside the container.

You may want to read https://github.com/lxc/lxd/blob/master/doc/storage-backends.md

**Comment by hatched** [comment]
Understood, thanks for your time.
