### ISSUE TITLE
Recovery from memory segmentation fault

### ISSUE THREAD

**Issue by naisanza** [lxc/lxc#1196]
I ran a java application with environmental variables for setting the maximum memory usage to a number greater than the amount of RAM allocated to the container (container was set with 512 MB, but java was run to request 2 GB). After running the command the container segfaulted (and was shown in dmesg).

`ES_JAVA_OPTS='-Xms2048m -Xmx2048m'`

Stopping all container and restarting them with the java command disabled does not fix this

from inside "test" container:
```
root@test:~# free -hm
total        used        free      shared  buff/cache   available
Segmentation fault
root@test:~# free
total        used        free      shared  buff/cache   available
Mem:         524288   -10043000      524176      473252    10043112      524176
Swap:       4849660       97488     4752172
```

I thought this was related to https://bugzilla.redhat.com/show_bug.cgi?id=1124722 , where `free` and `top` doesn't work inside linux containers, but I didn't see it segfault for them

**Comment by brauner** [comment]
Please specify the version of `LXC` (e.g. `lxc-start --version`), and `LXCFS` (e.g. `lxcfs --version`).

**Comment by naisanza** [comment]
@brauner 

lxc-start --version: `1.1.5`

lxcfs --version: 
```
hierarchies:
0: pids
1: hugetlb
2: perf_event
3: net_cls,net_prio
4: freezer
5: devices
6: memory
7: blkio
8: cpu,cpuacct
9: cpuset
10: name=systemd
2.0.0.beta1
```

**Comment by brauner** [comment]
Ok, so this may be caused by an outdated version of `LXCFS`. Please upgrade to the latest `LXCFS` version (Which should be `2.0.3`.). Also note that `LXC 1.1.*` is `EOL` (See https://linuxcontainers.org/lxc/news/.) which means we do not support it anymore and won't backport patches. Please upgrade to `LXC 2.0.4`. If the issue still persists with up-to-date `LXC` and `LXCFS`, please feel free to reopen.
