### ISSUE TITLE
URGENT Impossible to connect to any container from the same network

### ISSUE THREAD

**Issue by falves1** [lxc/lxc#1284]
The issue is very simple, and it started a few days ago, after an update.
You cannot communicate from the same network to a container, but from the container you can initiate any connection just fine. Also from outside my network I can ssh into a container and ping it. From the same network I cannot even ping a container.
I did not change anything on my end, except the daily update to my hosts, 
Ubuntu 16.04.1 LTS (GNU/Linux 4.4.0-45-generic x86_64)
This happens in two separate sites, so the issue is LXC, not my network.

Strange enough, if I run this command from another computer, not a container, on the same network, it works,
arping -I eth0 ip.add.res.ss 
where the IP address is the container's

so what does it all mean?

**Comment by stgraber** [comment]
Closing this issue as nothing changed in LXC which would explain such behavior. Such network problems are usually related to firewalling, misconfiguration or in the worst case, a kernel bug.

Since you've already posted about this on the lxc-users list, I suggest we keep the conversation going on there rather than in this issue.
