### ISSUE TITLE
Unable to access /proc/sys/net/ipv4/tcp_congestion_control inside LXC container. 

### ISSUE THREAD

**Issue by usama6naseer** [lxc/lxc#1285]
I am using 3.13.0-79-generic linux. Once I am inside lxc container I am unable to access /proc/sys/net/ipv4/tcp_congestion_control as the tcp_congestion_control file is missing. "sysctl net.ipv4.tcp_available_congestion_control" gives the available congestion mechanisms when called from outside the container. But inside container, it gives the error that tcp_congestion_control file or directory does not exist.

**Comment by stgraber** [comment]
I can confirm this behavior on the latest 4.8 kernel. This is a kernel issue rather than a LXC one though, there's nothing that LXC can do about files that are missing inside network namespaces.

I've confirmed the behavior in both a privileged and unprivileged container, so this is looks like a network namespace issue rather than a user namespace one.

Based on your kernel version, it looks like you're using Ubuntu, so I'd recommend you file a bug against the Linux kernel at https://launchpad.net/ubuntu/+source/linux/+filebug

Feel free to quote the above.
