### ISSUE TITLE
Can we get a template for Kali Linux ?

### ISSUE THREAD

**Issue by lethargic87** [lxc/lxc#140]
hi there
I was wondering if there is a template for Kali (new BackTrack) in the way?!
As you know this distro is mostly used for penetration and security reasons and it is not suitable for everyday use so we use it mostly in VMs! I think a template for this specific distro can help a lot of people as full Virtualization uses a lot of resources and is cumbersome! 
thanks

**Comment by ak2766** [comment]
I'm late to the party.

Even if Kali can run inside LXC, I doubt it will be possible to do any wifi hacking - educate me please!

ak.

**Comment by postfix** [comment]
https://testpurposes.net/2015/05/05/using-lxc-containers-to-partially-replace-virtual-machines/

**Comment by Kentoseth** [comment]
Going back to this old issue (I am working on sweeping up LXC issues), I don't think using Kali within LXC is as good an idea as using a full VM layer (these are my own security considerations - but everyone is entitled to their own opinions).

With that being said, @lethargic87 have you tested out @vince06fr's suggestion?

This issue is quite old, so it will be a good idea to resolve it.

**Comment by brauner** [comment]
As it seems that kali can simply be created from debian I think we can close this issue. Feel free to reopen if I'm wrong.
