### ISSUE TITLE
Network interface configuration depending on kernel PCI address

### ISSUE THREAD

**Issue by timofurrer** [lxc/lxc#1426]
If I have an udev rule like this:

```
ACTION=="add", SUBSYSTEM=="net", SUBSYSTEMS=="pci", KERNELS=="0000:01:00.0", NAME="net0"
```

Is there a way to emulate this PCI address in LXC? The documentation does not mention anything like that. The closest config was the `lxc.network.hwaddr` which does not help in this case.

**Comment by brauner** [comment]
No, there's no way to emulate the PCI address. In contrast to VM's the devices you hand in the container are exactly the same device as on the host. So assigning a new PCI address won't work. Additionally, udev rules won't work inside containers since only the init network namespace receives uevents. Sorry.
