### ISSUE TITLE
Fedora httpd rpm install error: unpacking of archive failed - cpio: cap_set_file

### ISSUE THREAD

**Issue by makgab** [lxc/lxc#1492]
Hi!
I'm trying the LXC under Fedora 25 x64 host.
I created a container with fedora25 template:
lxc-create -n fedora25 -t fedora

It runs, and I can attach to it. But in container:
`
dnf update
dnf install httpd

...

Error unpacking rpm package httpd-2.4.25-1.fc25.x86_64
Error unpacking rpm package httpd-2.4.25-1.fc25.x86_64
error: unpacking of archive failed on file /usr/sbin/suexec;58da9f30: cpio: cap_set_file

...

`

What is the problem? Is the package "httpd" wrong?

**Comment by stgraber** [comment]
That's because of missing kernel support for filesystem capabilities in user namespaces.
@hallyn wrote a patch for it which should hopefully be included in a kernel release soon.

Until then, you should stay away from anything which uses filesystem capabilities inside unprivileged containers, or run those containers as privileged.

**Comment by makgab** [comment]
The "httpd" package runs fine in CentOS7 container (in same host).
How can I set privileged container? I read this: https://linuxcontainers.org/lxc/security/

>  the container uid 0 is mapped to the host's uid 0
How can I set that?
