### ISSUE TITLE
Compatibility with OCI specifications

### ISSUE THREAD

**Issue by lifeng68** [lxc/lxc#1700]
Hi, Is there any  corresponding development plan to make LXC compatible with OCI spec?

**Comment by stgraber** [comment]
Nope, none at all. LXC mostly cares about system containers rather than application containers which the OCI spec focuses on. Also the design of LXC is a C library with language bindings and a few tools around it, rather than the single binary with standard interface approach that OCI takes.

Someone could certainly build an OCI compatible runtime using liblxc but it's not something we're likely to work on ourselves.
