### ISSUE TITLE
Do not pass <container-name> lxc <hook-name> to hooks

### ISSUE THREAD

**Issue by tanyifeng** [lxc/lxc#1766]
In function [run_script_argv](https://github.com/lxc/lxc/blob/04ba27e0dc8d7a72bfea263bf60219defec5af21/src/lxc/conf.c#L513), we bind command buffer with script, name, section, hook.

Assume that we configured `lxc.hook.pre-start = /usr/bin/touch /mytestfile`, and container name is "test1", then command buffer would be `"/usr/bin/touch /mytestfile  test1 lxc pre-start"`, executing this command will touch four files, which is not what we want.

Besides, if we want to bind script and its argv in [bind_real_argv](https://github.com/lxc/lxc/blob/04ba27e0dc8d7a72bfea263bf60219defec5af21/src/lxc/conf.c#L522), we will get wrong command buffer which is `"scrpit name section hook argv[0] argv[1] ..."`

Can we send a PR to fix this ?

**Comment by brauner** [comment]
I fail to reproduce the problem you are describing see:

[![asciicast](https://asciinema.org/a/135413.png)](https://asciinema.org/a/135413)

**Comment by tanyifeng** [comment]
Sorry for my poor presentation, actually if your check your root directory ` "/"` after executing pre-start script, there should be three empty file, `lxc a pre-start`.

The reason is, we use` lxc_popen` to run `buffer` in function [run_buffer](https://github.com/lxc/lxc/blob/04ba27e0dc8d7a72bfea263bf60219defec5af21/src/lxc/conf.c#L530), and the `buffer` is generated at [here](https://github.com/lxc/lxc/blob/04ba27e0dc8d7a72bfea263bf60219defec5af21/src/lxc/conf.c#L513) and [here2](https://github.com/lxc/lxc/blob/04ba27e0dc8d7a72bfea263bf60219defec5af21/src/lxc/conf.c#L522). So the finally buffer to run is " `"/usr/bin/touch /mytestfile  a lxc pre-start"`"

**Comment by brauner** [comment]
@tanyifeng, thanks for figuring this out! Yeah, if you want to send a patch, please go ahead. @hallyn, do you have an idea why the script is run like this?

**Comment by brauner** [comment]
Hm, when reading the manpage I realize that we explicitly state that these are passed as command line arguments to the script itself. So this is intended behavior. I'm missing the rationale currently so before going ahead with the patch I'd suggest we wait for input from @stgraber and @hallyn. There smart guys I've heard, they might have something to say. ;)

**Comment by hallyn** [comment]
If you look through the git history, you can see this is actually a side effect of using the run_script which has historically always passed that information along, since it was introduced for network.up hook in commit e3b4c4c44ae909ba5073edca975bc42ff007d9c9 .

I think it's worth considering dropping this (for things other than network.up and network.down) for 3.0.

**Comment by brauner** [comment]
@hallyn, yeah I looked at the git history. I was wondering whether - apart from legacy behavior - there was an underlying conceptual idea. :)

**Comment by hallyn** [comment]
So the first steps are:

1. Pass all the argv data along in env
2. As discussed elsewhere, provide a version or legacy key we can use to detect when not to pass args over argv.

Anyone have time to do these? If not, these need to be done asap (to have time to setlle before we can proceed) so maybe I'll take it.

**Comment by hallyn** [comment]
As a reminder, the way (2) above would likely look:

Lxc.hook.version = 1

If unset, defaults to 0, args are sent.

If set to 1, args are sent only as environment variables. 

Any other value, bail (i.e. reserved for future use)

**Comment by stgraber** [comment]
lxc.hook.version sounds good. You won't get to mix and match new and old hooks but that's probably fine.

**Comment by brauner** [comment]
Yeah, I agree. I first thought versioning the whole config like we once discussed would be a good idea but then you run into exactly the issue where you cannot mix and match different config keys. Having it specific for the hooks is nice.

What about 3.0 though? I would like to drop the hook arg passing entirely and just set env variables. So that we can cleanly drop any legacy config keys like we intended and commented in the code.

**Comment by hallyn** [comment]
@brauner the problem is people will want to use legacy configs with v3, and you can't parse just the config to verify that the hooks dtrt.

If we want to mix and match old and new the we could of course (only or also) support 'lxc.v2hook', but I don't think that's worthwhile. More onerous actually for the user.

**Comment by brauner** [comment]
Iirc, the plan was starting with `3.0` to drop the legacy configuration parser. Hence, you can only have configurations that have the new configuration keys set. For the hooks it probably makes sense to have `lxc.hook.version` since it's a change in behavior not a change in config key.

**Comment by brauner** [comment]
I sent patches to get rid of the args in https://github.com/lxc/lxc/pull/2017 since we need to do it soon and it seemed no one was working on this.
