### ISSUE TITLE
Have lxc group so users can do chown

### ISSUE THREAD

**Issue by haraldrudell** [lxc/lxc#1798]
When creating an unprivileged container, the produced root file system needs to be owned by the mapped root user, like 100000.

Modifying this ownership requires sudo, unless there's some fancy feature I don't know about.

lxc could fix that by having an lxc group and a chmod script that group members can execute with sudo without having to manually input a password. This would be great for automation.

like lxc-config --set-owner --name=myUnpriviligedContainer
- fetches the uid:gid from container config file
- runs chown --recursive on the containers root file system without sudo password input

**Comment by stgraber** [comment]
There's no reason to add more setuid helpers to LXC or special groups.

If your user owns those uid/gid (which must be the case otherwise you couldn't create the container in the first place), then you can use something like the lxc-usernsexec tool to setup a map that will let you see both your own user's uid/gid and the subuid/subgid map of your container at which point you can remap things as you want.

**Comment by stgraber** [comment]
None of that subuid/subgid handling is specific to LXC. LXC just uses the files and tools provided by the shadow package. If there's a need for extra utilities to interact with those subuids and subgids, then that should be done in shadow.
