### ISSUE TITLE
Add a hook for CNI network up

### ISSUE THREAD

**Issue by hallyn** [lxc/lxc#1812]
This should be done from the host's namespaces, and probably after mounts are up.  Find the best place.

**Comment by brauner** [comment]
@hallyn, this might be perfect for the gpu hook as well. In essence, the gpu hooks need to add rules to the devices cgroup for privileged containers. This is something which we can't do in the `lxc.hook.mount` hook since we clear the devices cgroup setting afterwards. So having a hook run in the host's namespaces might be perfect for that. I thought about `lxc.hook.pre-exec` (or a better name) which basically runs in the parent's namespaces right before:

    if (lxc_sync_barrier_child(handler, LXC_SYNC_POST_CGROUP))

where the device cgroup limits have been setup and all mounts have been performed as well. The only thing is that we'd need to set something like `LXC_CGROUP_PATH` as an env variable so that the hook could access this information.

**Comment by hallyn** [comment]
Hm, does that mean we'd need a need a new cgroup callback to give us the 'base_cgroup'?

**Comment by brauner** [comment]
Hm, we could but wouldn't it be sufficient to either call `lxc_cmd_get_cgroup_path()` and give the user the cgroup without the mountpoint?

**Comment by hallyn** [comment]
> Hm, we could but wouldn't it be sufficient to either call `lxc_cmd_get_cgroup_path()` and give the user the cgroup without the mountpoint?

Just pick the freezer cgroup, making the assumption that it has to be available?

**Comment by brauner** [comment]
Hm, actually this is unpleasant if the user needs to know the path for a specific subsystem which could be different per-controller at least for unprivileged containers.

**Comment by hallyn** [comment]
> Hm, actually this is unpleasant if the user needs to know the path for a specific subsystem which could be different per-controller at least for unprivileged containers.

*technically* so long as we pass in the init pid, the script can figure
out the rest.

**Comment by brauner** [comment]
`cat /proc/<init-pid>/cgroup` should be sufficient for this. Yeah, I'd be ok with that.

**Comment by 3XX0** [comment]
We use `getppid()` right now for `/proc/.../mountinfo` and `/proc/.../cgroup` in the `mount.hook`.
If we have a new hook in the parent, exporting the child PID is probably the right thing to do.
That would be pretty much similar to what `runc` does.

**Comment by brauner** [comment]
Excellent, I'd like to have this settled soon so that @3XX0 can finish his gpu integration. :)

**Comment by hallyn** [comment]
@3XX0 - could you take a look at https://github.com/lxc/lxc/pull/1826 to make sure it suits your needs?

**Comment by 3XX0** [comment]
@hallyn If I understood correctly, not quite unfortunately.
The problem is that the hook is triggered after the child pivots, so if it's impossible to mount stuff at this point. 

Glancing at the code:
`lxc_sync_barrier_child(handler, LXC_SYNC_CGROUP_UNSHARE)` will wait for `LXC_SYNC_CGROUP_LIMITS` to setup the cgroups and run the hook but this will happen way after `lxc_setup()` (which does the pivot)

**Comment by 3XX0** [comment]
@brauner Yeah but there are in different mount namespaces so unless you do some `O_PATH` magic, you can't just `setns` to the child and bind mount what you need

**Comment by brauner** [comment]
@3XX0, ah, Al Viro's infamous can't mount a across mount namespaces patch which noone is sure why it exists. Ok. @hallyn, I say we proceed with this patch and not worry about the gpu use case. I'll try to "first" `lxc.hook.mount` instead the next few days. Place the hook to your convenience, @hallyn.

**Comment by 3XX0** [comment]
I guess we can rely on the `lxc.hook.mount` for the GPU use case but RDMA vendors might need this though. What would be the implications of moving the `LXC_SYNC_CGROUP_LIMITS` barrier above `lxc_setup`? Would it be problematic to set the cgroup early on?

**Comment by hallyn** [comment]
Done through PR #1826
