### ISSUE TITLE
Improve feedback "The configuration file contains legacy configuration keys. Please update your configuration file!"

### ISSUE THREAD

**Issue by krichter722** [lxc/lxc#1938]
The template below is mostly useful for bug reports and support questions.
Feel free to remove anything which doesn't apply to you and add more information where it makes sense.

# Required information

 * Distribution: Ubuntu
 * Distribution version: 17.10
 * The output of
   * `lxc-start --version`: 2.1.0

# Issue description
If a container contains invalid configuration keys in its `config` file, `lxc-start` fails due to

```
The configuration file contains legacy configuration keys.
Please update your configuration file!
```

I'd be very helpful if the invalid configuration key would be named or at least a reference where the information can be retrieved ("Don't make me think").

# Steps to reproduce

 1. create a container
 2. add an invalid configuration parameter to `config`
 3. start the container with `lxc-start --foreground`

# Information to attach

 - [ ] any relevant kernel output (`dmesg`)
 - [ ] container log (The <log> file from running `lxc-start -n <c> -l <log> -o DEBUG`)
 - [ ] the containers configuration file

**Comment by brauner** [comment]
The container shouldn't be prevented from starting just because it contains an legacy configuration key. If you look at the requested log file you can also retrieve all invalid configuration keys. We can probably print that information together with the warning message.
If you want to update your config file you should run our update script `lxc-update-config` that we ship with newer versions which is called as `lxc-update-config -c </path/to/config>`. If the update leads to an invalid config you can restore the legacy config by looking for the backed up config file in the path where the config resides.
