### ISSUE TITLE
lxc-start, opening log file fails with custom lxc.lxcpath

### ISSUE THREAD

**Issue by ousado** [lxc/lxc#198]
on debian sid, with a custom lxc.lxcpath in /etc/lxc/lxc.conf, lxc-start seems to still use the default path for the log file

$ sudo lxc-start -n debian2 -d
lxc-start: failed to open log file "/var/lib/lxc/debian2/debian2.log" : No such file or directory

**Comment by lazy404** [comment]
this is related to
https://github.com/lxc/lxc/blob/master/src/lxc/log.c#L359

"try LOGPATH if lxcpath is the default for the privileged containers"

if we change lxc.lxcpath in /etc/lxc/lxc.conf it still tries to use LOGPATH without creating dirs,
this will always fail because the container directorys are created at new lxcpath,

lxc_global_config_value("lxc.lxcpath") is not the default value, LXCPATH is

following https://github.com/lxc/lxc/commit/b6ac57f968a8eefcc580c86f8b94ca1ba406a674 logic
it should check if lxcpath equals LXCPATH not lxc_global_config_value("lxc.lxcpath")

**Comment by brauner** [comment]
Can be closed due to commit being merged.
