### ISSUE TITLE
A question about lxc-stop

### ISSUE THREAD

**Issue by lifeng68** [lxc/lxc#2082]
@brauner hi,
It may be a simple question, but it's been a long time for me.
I read the code about `lxc stop`, it just send the stop signal(default 'SIGKILL') to the container's init process. My question is: If there are multiple processes in the container, how does it perform  the function of killing all processes? They don't seem to belong to the same process group.

**Comment by lifeng68** [comment]
Is it related to PID namespace?

**Comment by brauner** [comment]
Hi @ligeng68, actually we only sent SIGKILL when --force is passed at which point the API calls stop(). Otherwise shutdown() is called.

Yes, the semantic of PID namespaces is such that when init dies aka when PID 1 dies the kernel considers the PID namespace disfunctional and SIGKILL all other processes in that PID namespace.

**Comment by brauner** [comment]
This is true of initial and non-inital namespaces. From the kernels perspective it makes perfect sense since without PID 1 there's no one to retrieve child statuses of processes whose parents have died. So you'd end up spamming the relevant PID namespace with zombies.

**Comment by lifeng68** [comment]
@brauner ,Thanks very much!
