### ISSUE TITLE
Make the parent process of container as a subreaper for the processes in container

### ISSUE THREAD

**Issue by lifeng68** [lxc/lxc#2302]
Now, if the processes in the container becomes orphaned (i.e., its immediate parent terminates) then that process will be reparented to the init(1). 
If we started a container which init process can not handle SIGCHLD to call wait() to reclaim the orphaned  process((i.e., /bin/bash).  Then the orphaned process will be  in Zombie state until the  container stopped.
I read the codes of containerd, the containerd make the  parent process of container as a subreaper for the processes in container.  So docker can reclaim the orphaned processes in that case.
Is it possible for LXC to adopt the same strategy?

**Comment by brauner** [comment]
> If we started a container which init process can not handle SIGCHLD to call wait() to reclaim the orphaned process((i.e., /bin/bash).

If I understand you correctly then that scenario should never happen if you run it through our minimal init aka: `c->start(c, 1, argv);` where `1` indicates that you're using the minimal init.

**Comment by brauner** [comment]
Can you give a reproducer that illustrates your problem with LXC?

**Comment by brauner** [comment]
Right, but that happens because you're running the container through `lxc-start` which always expects a functional init. On a more generic note pid namespaces in general always expect a functional init. This is built into their semantics. (I've [talked about this a while back](https://youtu.be/wiFWBhmFyOM?t=6m50s).)
What you'd want is to run all of this through `lxc-execute`. In this case you'd have a minimal init whose only job is to handle signals and reap children. If you kill it, the container will automatically die as well.

The subreaper solution is - excuse my bluntness - a terrible hack. No just that it explicitly violates or at least ignores pid namespace semantics also I bet what containerd is doing is to reap subprocesses based on a timer? We would be in a slightly better solution as we can have the monitor reap those children through the singal_handler but it still wrong and a hack.

Is there any reason why you can't use `lxc-execute`?
