### ISSUE TITLE
error while cloning container with ext4 file-system on lvm backingstore and snapshot mode

### ISSUE THREAD

**Issue by aston-r** [lxc/lxc#2375]
Dear Developers,

The issue reported here https://github.com/lxc/lxc/issues/2241 is still reproducible

[$]> lxc-copy --version
3.0.1

STR:
-create a container with lvm backingstore
-clone the container with snapshot mode
```
lxc-copy --logpriority=DEBUG \
         --name="1_masterdb" \
         --newname="2_masterdb" \
         --keepname \
         --snapshot \
         -- \
         --hook-path="${hook_path}" \
         -- \
            ${hook_options}
```

Actual Result:
-lvm snapshot is created but lxc-copy fails:

```
lxc-copy: 1_masterdb: storage/lvm.c: lvm_snapshot: 404 Failed to create new uuid for volume "/dev/mapper/2_masterdb": lxc-copy: 1_masterdb: utils.c: run_command: 2280 failed to exec command                                                
lxc-copy: 1_masterdb: storage/lvm.c: lvm_create_snapshot: 583 Failed to create lvm "lvm:/dev/mapper/2_masterdb" snapshot of "/dev/mapper/lxdata-1_masterdb"                                                                                  
lxc-copy: 1_masterdb: lxccontainer.c: copy_storage: 3449 Error copying storage.  

  --- Logical volume ---
  LV Path                /dev/lxdata/2_masterdb
  LV Name                2_masterdb
  VG Name                lxdata
  LV UUID                e3gbrc-bblI-Flwr-XYkV-SDwb-MKPH-DfIO9P
  LV Write Access        read/write
  LV Creation host, time lxbase, 2018-06-04 16:51:09 +0300
  LV Pool name           lxpool
  LV Thin origin name    1_masterdb
  LV Status              available
  # open                 0
  LV Size                15,00 GiB
  Mapped size            41,12%
  Current LE             3840
  Segments               1
  Allocation             inherit
  Read ahead sectors     auto
  - currently set to     8192
  Block device           253:7
```

Please check. TIA.

**Comment by krbvroc1** [comment]
@brauner @stgraber

I am new to LXC and this fails for me too. I saw https://github.com/lxc/lxc/issues/2241 was closed and it looks like the fix is only in 3.1. I do not see a 3.1 being available anyhwere. So I installed a PPA of the development branch/3.1 master. After upgrading, it still doesn't work!

I figured I would try xfs and that fails too with a different message:
```
lxc-create --name=alpine-edge --fstype=xfs --fssize=100M --bdev=lvm --thinpool=data_tpool --template=alpine -- --release=edge
lxc-create: alpine-edge: storage/storage_utils.c: mount_unknown_fs: 322 Failed to determine FSType for "/dev/data_vg/alpine-edge"
lxc-create: alpine-edge: lxccontainer.c: create_run_template: 1421 Failed to mount rootfs
lxc-create: alpine-edge: lxccontainer.c: create_run_template: 1633 Failed to create container from template
lxc-create: alpine-edge: tools/lxc_create.c: main: 331 Failed to create container alpine-edge
```

My intro to LXC has been a disaster. Should i be using lxc2? I didn't see that available for Ubuntu 18 LTS which I chose thinking it was 'stable'.

**Comment by aston-r** [comment]
@krbvroc1 
Please check that auto_set_activation_skip option is set to '0' in '/etc/lvm/lvm.conf'.

**Comment by ryba84** [comment]
The issue is still reproducible.

> ~# lxc-copy --version
3.0.3

With ext4 filesystem cannot create snapshots. Xfs works.

> lxc-copy debian64 20190928214517.753 DEBUG    storage - storage/storage.c:get_storage_by_name:231 - Detected rootfs type "lvm"
lxc-copy debian64 20190928214517.965 DEBUG    storage_utils - storage/storage_utils.c:find_fstype_cb:412 - Trying to mount "/dev/lxc/debian64"->"/usr/lib/x86_64-linux-gnu/lxc/rootfs" with FSType "ext3"
lxc-copy debian64 20190928214517.967 DEBUG    storage_utils - storage/storage_utils.c:find_fstype_cb:420 - Invalid argument - Failed to mount
lxc-copy debian64 20190928214517.967 DEBUG    storage_utils - storage/storage_utils.c:find_fstype_cb:412 - Trying to mount "/dev/lxc/debian64"->"/usr/lib/x86_64-linux-gnu/lxc/rootfs" with FSType "ext2"
lxc-copy debian64 20190928214517.968 DEBUG    storage_utils - storage/storage_utils.c:find_fstype_cb:420 - Invalid argument - Failed to mount
lxc-copy debian64 20190928214517.968 DEBUG    storage_utils - storage/storage_utils.c:find_fstype_cb:412 - Trying to mount "/dev/lxc/debian64"->"/usr/lib/x86_64-linux-gnu/lxc/rootfs" with FSType "ext4"
lxc-copy debian64 20190928214517.982 INFO     storage_utils - storage/storage_utils.c:find_fstype_cb:428 - Mounted "/dev/lxc/debian64" on "/usr/lib/x86_64-linux-gnu/lxc/rootfs", with FSType "ext4"
lxc-copy debian64 20190928214518.100 INFO     storage_utils - storage/storage_utils.c:detect_fs:240 - Detected FSType "ext4" for "/dev/lxc/debian64"
lxc-copy debian64 20190928214518.107 ERROR    utils - utils.c:run_command:1615 - Failed to exec command
lxc-copy debian64 20190928214518.114 ERROR    lvm - storage/lvm.c:lvm_snapshot:406 - Failed to create new uuid for volume "/dev/lxc/ns1": lxc-copy: debian64: utils.c: run_command: 1615 Failed to exec command
lxc-copy debian64 20190928214518.115 ERROR    lvm - storage/lvm.c:lvm_create_snapshot:585 - Failed to create lvm "lvm:/dev/lxc/ns1" snapshot of "/dev/lxc/debian64"
lxc-copy debian64 20190928214518.115 ERROR    lxccontainer - lxccontainer.c:copy_storage:3567 - Error copying storage.
lxc-copy debian64 20190928214518.125 INFO     lxccontainer - lxccontainer.c:container_destroy:3042 - Destroyed directory "/var/lib/lxc/ns1" for "ns1"
lxc-copy debian64 20190928214518.126 ERROR    lxc_copy - tools/lxc_copy.c:do_clone:371 - Failed to clone

**lvm_snapshot_create_new_uuid_wrapper** from **storage/lvm.c** supports only btrfs and xfs.

**Comment by starkovv** [comment]
+1

**Comment by stgraber** [comment]
@brauner can you look into this? Sounds like we need a UUID re-gen of some kind.
