### ISSUE TITLE
lxc-autostart does not signal failures using exit status codes

### ISSUE THREAD

**Issue by thedrow** [lxc/lxc#2523]
# Required information

Applicable in any environment and is reproducible at least at 3.0+ but probably in earlier versions as well.

# Issue description

I just set up a systemd service to run my unprivileged containers on boot.
The containers failed to start correctly but the service is still marked as active since the command line [always exits with a 0 status code](https://github.com/lxc/lxc/blob/master/src/lxc/tools/lxc_autostart.c#L507) unless a CLI parsing option occurred, initializing the logger fails or if there are no defined containers to start.
This makes retries and error reporting much harder.

I suggest we reserve exit code 2 for partial failures (not all containers were started/shutdown etc) and exit code 3 for full failures. We can alternatively reuse exit code 1 if that's the right path in your opinion.

# Steps to reproduce

Create the following systemd service in /home/<user>/.config/systemd/user/lxc-autostart.service:

```ini
[Unit]
Description=Start LXC containers on boot

[Service]
Type=oneshot
ExecStart=/usr/bin/lxc-autostart
ExecStop=/usr/bin/lxc-autostart --shutdown
RemainAfterExit=yes

[Install]
WantedBy=default.target
```

Type `systemctl --user daemon-reload && systemctl --user enable lxc-autostart`.

Reboot.

The service will fail to start since dependency order was not declared and lxc has not been set up correctly yet.
Note that this is probably the wrong systemd configuration and the service should be configured as a system service in order to boot correctly.

# Information to attach

N/A

**Comment by stgraber** [comment]
Sure, having lxc-autostart fail when it failed to start some containers is reasonable.

systemd distros shouldn't be using lxc-autostart directly though, they should use lxc-autostart with `--list` to get the list of containers and then spawn individual instances of a `lxc` unit for each of those.
That way you get per-container units with their own status and retry policy.

Upstream already ships a `lxc@.service` unit which then allows you to do `systemctl start lxc@blah` to start container `blah`, but the main `lxc.service` unit itself doesn't seem to be making use of that, so that'd be something to improve if someone has the interest to do that.

**Comment by thedrow** [comment]
@stgraber How do you prefer the exit codes to behave?
