### ISSUE TITLE
[RFC] impact on template downloads in view of SKS Keyserver Network Attack

### ISSUE THREAD

**Issue by ghost** [lxc/lxc#3068]
To my humble understanding the template downloads are verifying signatures via SKS and thus appreciate clarification whether and to which potential extent the download process could be impacted by

## SKS Keyserver Network Under Attack

> This attack cannot be mitigated by the SKS keyserver network in any reasonable time period. 
> The best mitigation that can be applied at present is simple: stop retrieving data from the SKS keyserver network.

https://gist.github.com/rjhansen/67ab921ffb4084c865b3618d6955275f

**Comment by stgraber** [comment]
My understanding is that the SKS attack effectively allows for replacing a valid public key entry with a broken/unreadable one, effectively preventing the retrieval of the public key from the SKS network.

So that's effectively a DoS attack. It will not allow an attacker to replace the key with their own so they will not be able to cause systems running LXC to run compromised content.

I think that in the next LXC release, we'll want to take the same approach we did with LXD and remove the GPG handling code, instead requiring the index files be downloaded over HTTPs and then validate the artifacts against the signatures found in those index files.

**Comment by dereks** [comment]
This is an ongoing issue for 7 weeks now. What is happening with SKS? Has there been a DoS attack for the past two months, or is this an IPv6 misconfiguration that they can fix?

This was also discussed here, with some workarounds and further info:

https://discuss.linuxcontainers.org/t/3-0-unable-to-fetch-gpg-key-from-keyserver/2015/13

It seems like very LXC user is affected. I finally got it to work with this DOWNLOAD_KEYSERVER but I don't know if that's what fixed it or my 4th attempt was my lucky number.

```
export DOWNLOAD_KEYSERVER="ipv4.pool.sks-keyservers.net"
lxc-create -t download ...etc...
```

**Comment by stgraber** [comment]
Not aware of any large scale issue with sks.

**Comment by dereks** [comment]
I just read the community post in the linked discussion (here is the link again):

https://gist.github.com/rjhansen/67ab921ffb4084c865b3618d6955275f

This is the executive summary posted by the GPG team member:

> This attack cannot be mitigated by the SKS keyserver network in any reasonable time period. It is unlikely to be mitigated by the OpenPGP Working Group in any reasonable time period. Future releases of OpenPGP software will likely have some sort of mitigation, but there is no time frame. The best mitigation that can be applied at present is simple: stop retrieving data from the SKS keyserver network.

Other tidbits:

> We've known for a decade this attack is possible. It's now here and it's devastating. There are a few major takeaways and all of them are bad.

- If you fetch a poisoned certificate from the keyserver network, you will break your GnuPG installation.
- Poisoned certificates cannot be deleted from the keyserver network.
- The number of deliberately poisoned certificates, currently at only a few, will only rise over time.
- We do not know whether the attackers are intent on poisoning other certificates.
- We do not even know the scope of the damage.


Based on that post, this seems absolutely devastating. "The best mitigation that can be applied at present is simple: stop retrieving data from the SKS keyserver network." (!!!) He also says the SKS server software is "Byzantine" and "unmaintained", which is bad enough on its own without an active DoS attack underway.

I would encourage the LXC team to escalate this issue as high priority.

I respectfully disagree with @stgraber 's HTTPS solution proposed above. With GPG, the package I downloaded can be traced to an individual human being, i.e., the author of the software, even if I obtained the software from an untrusted network. But with HTTPS, the only guarantee of trust is the public SSL server certificate. That SSL certificate might even be a wildcard cert for the whole domain, or it might reside on some proxy server elsewhere in the organization.

**Just because the domain's Apache administrator got a free SSL certificate from Let's Encrypt does not mean they guy who posted the .asc or .sha256 package signature (or index file) has anything to do with the upstream source code.**

All it would take to create a huge botnet of compromised LXC servers is to post a trojan image. If the attacker can post a trojan image he already has all the permissions necessary to also post a new "valid" signature for that poisoned package file.

**Distribution systems whose trust is based solely on a web SSL certificate are not secure.** This includes any software installed with wget or curl, like Android's repo and PHP's composer. Please don't make LXC fall into that category.

**Comment by dereks** [comment]
Ok, apologies, my bad on being late to the party. That core SKS issue is over a year old now:

https://lwn.net/Articles/792494/

So either the keyserver community has already moved to alternate networks, or the attack is slow enough to be mitigated. I misread a date and thought this attack was something new, and was expecting a keyserver meltdown.

The first link (above) about this error mentions IPv4 vs. IPv6 being a problem. From

https://discuss.linuxcontainers.org/t/3-0-unable-to-fetch-gpg-key-from-keyserver/2015/12

> Meantime I did some more reading on the subject and further testing and it seems that it bears down to a dns resolution issue when ipv6 is involed, and this lxc host is pure ipv4.

As soon as I changed to the ipv4 dedicated server, my problem disappeared. It might be related, not sure.

```
export DOWNLOAD_KEYSERVER="ipv4.pool.sks-keyservers.net"
lxc-create -t download ...etc...
```

But the SKS issue also still seems to be an open issue so who knows.

WIth this context in mind I would recommend switching to one of the other keyserver solutions mention in the LWN article above, so LXC is immune from the SKS vulnerability (which seems to still be open) but has the security of a GPG "web of trust", rather than just an SSL certificate (which is a pretty low bar).

**Comment by mihalicyn** [comment]
Not actual anymore because of https://github.com/lxc/lxc/pull/4062.

> I respectfully disagree with @stgraber 's HTTPS solution proposed above. With GPG, the package I downloaded can be traced to an individual human being, i.e., the author of the software, even if I obtained the software from an untrusted network.

I'm not an expert in that, but as far as I understand we also provide SHA256SUMS file for the images and GPG signature for this file too. This should cover your argument.
Example:
https://images.linuxcontainers.org/images/almalinux/8/amd64/cloud/20240219_23:08/SHA256SUMS.asc

@stgraber should we close this?

**Comment by stgraber** [comment]
Yeah, the reality is that none of this was ever signed by human beings, it's all automated anyways.

And as you point out, the actual files can still be validated through GPG if someone really wants to. We just don't want to rely on GPG working as expected as it really hasn't for years now.
