### ISSUE TITLE
Is it possible to hide host's disk information from unprivileged containers ?

### ISSUE THREAD

**Issue by ss-17** [lxc/lxc#3224]
Hello,

I am using unprivileged containers with directory back-end for rootfs. The thing is `df` output inside the container displays the entire information of host's mount on which this rootfs directory is stored. For example if I have /dev/sdb mounted as /mnt/sdb on host with rootfs for a `container A` stored in `/mnt/sdb/A`, a `df -h` inside the container will display:

```
Filesystem              Size  Used Avail Use% Mounted on
/dev/sdb               1000G  632G  368G  63% /
none                    492K     0  492K   0% /dev
udev                    959M     0  959M   0% /dev/tty
tmpfs                   974M     0  974M   0% /dev/shm
tmpfs                   974M  8.1M  966M   1% /run
tmpfs                   5.0M     0  5.0M   0% /run/lock
tmpfs                   974M     0  974M   0% /sys/fs/cgroup
```

As you can see it displays the full size, usage etc of /dev/sdb. Is there a way to hide this information from the container?

Thanks.

**Comment by Blub** [comment]
Best you can do is catch the `statfs` sycall with seccomp, since lxc now supports proxying caught syscalls from seccomp to an external program, you can implement a small-ish custom handler for it. However, if you intend to turn it into the equivalent of a `du` on the directory it'll become really slow ;-)
This isn't lxc's responsibility (and for directories very unpleasant to do).

**Comment by brauner** [comment]
I think @Blub gave a great answer to this. Thanks!
