### ISSUE TITLE
Permission issues in lxc container after adding a device

### ISSUE THREAD

**Issue by VyshakhKrishnan** [lxc/lxc#3246]
I am trying to access host machines devices:

rtbrick@VYSHAKH:/dev$ ls -ltr /dev/vhost-net 
crw-rw-rw- 1 root root 10, 238 Jan  1 17:25 /dev/vhost-net
rtbrick@VYSHAKH:/dev$ ls -ltr /dev/net/tun 
crw-rw-rw- 1 root root 10, 200 Jan  1 17:26 /dev/net/tun

into lxc container:

rtbrick@VYSHAKH:/dev$ sudo lxc-ls -f vpp3
NAME STATE   AUTOSTART GROUPS IPV4                 IPV6 UNPRIVILEGED 
vpp3 RUNNING 0         -      10.0.3.162, 10.0.4.1 -    false        

with the command:

rtbrick@VYSHAKH:/dev$ sudo lxc-device -n vpp3 add /dev/net/tun
rtbrick@VYSHAKH:/dev$ sudo lxc-device -n vpp3 add /dev/vhost-net 

I could see the device files in lxc container :

ubuntu@vpp3:~ $ 
ubuntu@vpp3:~ $ ls -ltr /dev/vhost-net
crw-r--r-- 1 root root 10, 238 Jan  1 13:18 /dev/vhost-net
ubuntu@vpp3:~ $ ls -ltr /dev/net/tun
crw-r--r-- 1 root root 10, 200 Jan  1 13:18 /dev/net/tun
ubuntu@vpp3:~$ 

but i am able to access only one of it though both are accessible in the host machine and the permissions are all fine:

ubuntu@vpp3:~ $ cat /dev/net/tun
cat: /dev/net/tun: File descriptor in bad state
ubuntu@vpp3:~ $ 
**ubuntu@vpp3:~ $ cat /dev/vhost-net
cat: /dev/vhost-net: Operation not permitted**
ubuntu@vpp3:~ $ 

**ubuntu@vpp3:~ $ sudo cat /dev/vhost-net
cat: /dev/vhost-net: Operation not permitted
ubuntu@vpp3:~ $ sudo su
root@vpp3:/home/ubuntu# cat /dev/vhost-net
cat: /dev/vhost-net: Operation not permitted
root@vpp3:/home/ubuntu#** 

Am i missing anything here?

**Comment by stgraber** [comment]
`vhost-net` doesn't work in containers. I'm not exactly sure why, but I've tried it before and the kernel just isn't happy with it. I'm pretty sure this is because that kernel feature simply isn't network namespace aware. It would also need some very weird bits of kernel interface to work since it requires char devices to appear, which is also not something that's namespaced.

`/dev/net/tun` works fine, it's just not meant to be `cat`, you'll get the same behavior on the host.

**Comment by VyshakhKrishnan** [comment]
Adding the cgroup devices allow in lxc config file resolved this issue :

/usr/share/lxc/config/common.conf :

### /dev/vhost-net
lxc.cgroup.devices.allow = c 10:238 rwm
