### ISSUE TITLE
Adding second interface on LXC, NIC -1 Bridge to WAN, NIC -2 Bridge to LAN

### ISSUE THREAD

**Issue by myshamim** [lxc/lxc#3326]
I have facing an issue in adding a second NIC in LXC. In my scenario LXC contains 2 x NICs, one is connected to WAN with public IP and other one is connected to LAN on private IP.

By default how the LXC reaches to internet,  the lxcbr0 is not bridge to outside NIC or where can I validate it. 

I am using Ubuntu 18.04

sudo iptables -t nat -nL
Chain PREROUTING (policy ACCEPT)
target     prot opt source               destination         

Chain INPUT (policy ACCEPT)
target     prot opt source               destination         

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         

Chain POSTROUTING (policy ACCEPT)
target     prot opt source               destination         
MASQUERADE  all  --  10.0.3.0/24         !10.0.3.0/24    

ip route show
default via 192.168.1.1 dev ens33 proto dhcp metric 100 
10.0.3.0/24 dev lxcbr0 proto kernel scope link src 10.0.3.1 
169.254.0.0/16 dev lxcbr0 scope link metric 1000 
192.168.1.0/24 dev ens33 proto kernel scope link src 192.168.1.4 metric 100

**Comment by stgraber** [comment]
`lxcbr0` runs its own subnet which is NATed to the internet.

That's what you're seeing above as the MASQUERADE rule in `POSTROUTING`.

LXC is using the `10.0.3.0/24` private subnet for your containers and all outgoing connections from them get masqueraded (SNAT).

If you want LXC containers to be directly bridged to the network, then you need to manually create those bridges through your Linux distributions and then configure your containers to use those rather than the default lxcbr0.

Closing as this isn't a bug report but a support question. Those tend to be better handled through https://discuss.linuxcontainers.org

**Comment by myshamim** [comment]
Thank you for your comment.
