### ISSUE TITLE
cgroup path in containers depends on lxc version

### ISSUE THREAD

**Issue by LynxChaus** [lxc/lxc#3373]
I'm observer strange behavior - when using lxc-3.2.1 lxc-attach /proc/self/cgroup setup is normal
```
# lxc-attach test -- cat /proc/self/cgroup
13:rdma:/
12:pids:/
11:hugetlb:/
10:net_prio:/
9:perf_event:/
8:net_cls:/
7:freezer:/
6:devices:/
5:memory:/
4:blkio:/
3:cpuacct:/
2:cpu:/
1:cpuset:/
0::/
```
when using same container with 4.0.1 lxc-attach /proc/self/cgroup setup show strange '0::/.lxc':
```
# lxc-attach test -- cat /proc/self/cgroup
13:rdma:/
12:pids:/
11:hugetlb:/
10:net_prio:/
9:perf_event:/
8:net_cls:/
7:freezer:/
6:devices:/
5:memory:/
4:blkio:/
3:cpuacct:/
2:cpu:/
1:cpuset:/
0::/.lxc
```
why?

**Comment by brauner** [comment]
With LXC 4.0 we added full cgroup2 support and one of the fundamental requirements of cgroup2 is that only leaf nodes can contain live processes. So when you attach to a container and an init system manages cgroups (e.g. as systemd does) than the root cgroup of the container will not be a leaf node and thus no processes can exist in there so we need to have an empty subcgroup that we can attach to. That's .lxc.

**Comment by brauner** [comment]
See some more details around cgroup2 in our release announcement:
https://discuss.linuxcontainers.org/t/lxc-4-0-lts-has-been-released/7182

**Comment by LynxChaus** [comment]
Our problem - every process run in lxc-attach session moved to .lxc control group. This behavior different form all other in system.

**Comment by brauner** [comment]
So the restriction I mentioned is a kernel-enforced restriction and so not something we can really work around. The unified hierarchy is very much different from the legacy hierarchy.

**Comment by LynxChaus** [comment]
Why this not described in "major changes" in release notes of 4.0 ?

**Comment by brauner** [comment]
On Sun, Apr 12, 2020 at 04:47:25AM -0700, Andrey Jr. Melnikov wrote:
> Why this not described in "major changes" in release notes of 4.0 ?

We have not explicitly called out the attaching .lxc cgroup as this was
a rather recent change for LXC 4.0.1 and we certainly should have done
that but we explained in detail for the LXC 4.0 release announcement
that the on-disk layout of cgroups would need to change because of the
unified hierarchy. We've also said quite often that relying on the
on-disk layout that LXC uses should be avoided. Not because we don't
_want_ to make guarantees but because we _can't_ make guarantees given
how much cgroup2 has diverted from the legacy cgroup filesystem already
and we aren't confident enough that the kernel won't make a drastic
change in this particular area again.
