### ISSUE TITLE
Error: open /var/lib/snapd/instance/path/file no such file or directory

### ISSUE THREAD

**Issue by jamielsharief** [lxc/lxc#3451]
I am trying to copy a file from one instance to another instance
`lxc file push c1/var/www/config/.env c2/root/.env`

And it gives me the following error
`Error: open /var/lib/snapd/c1/var/www/config/.env: no such file or directory`

Also the the path the path `/var/lib/snapd` is empty but the file exists in the container,  and if I run `lxc file pull c1/var/www/config/.env .` it works fine.

I think this might be a path bug.

**Comment by stgraber** [comment]
`lxc file push` doesn't support copying from one instance to another.

The error is quite weird because of all the hoops we jump through to find the path you've provided while being in a constrained snap environment, but it effectively boils down to "c1/var/www/config/.env" doesn't exist relative to your current directory.

To do what you want, you need to pull and push the file.

This can be done with something like: `lxc file pull c1/var/www/config/.env - | lxc file push - c2/root/.env`

**Comment by jamielsharief** [comment]
Sorry I misunderstood the usage.
