### ISSUE TITLE
lxc-attach: testcontainer: terminal.c: lxc_terminal_create_native: 934 Inappropriate ioctl for device - Failed to allocate new pty device

### ISSUE THREAD

**Issue by marcfiu** [lxc/lxc#3625]
Compiled LXC 4.0.5 for CentOS 7.

# Required information
 * Distribution: CentOS
 * Distribution version: 7.9
 * CentOS 7.9 uses a 3.10 based kernel

# Issue description
Upon attaching to a running container get a false positive warning:
```
lxc-attach: testcontainer: terminal.c: lxc_terminal_create_native: 934 Inappropriate ioctl for device - Failed to allocate new pty device'
```

The code then does fall back to correctly get a pty, as shown:
```
[root@testcontainer ~]# tty
/dev/pts/2
```

# Steps to reproduce
 1. compile LXC 4.0.5 on CentOS 7
 2. create a container
 3. lxc-attach to container from step 2

# Possible fix
We fixed it by checking whether the kernel version was 4.13 or below at runtime. Why a run-time check, because some EL7 based systems might run a more modern kernel (eg cloudlinux, oracle linux + uek, or anyone running kernel-ml or whatnot from elrepo), for which doing the TIOCGPTPEER  ioctl is the right thing. However, there may well be a better/cleaner approach, which is why I am posting here for further feedback.

Please advise. Happy to fork and submit a tested PR based on your feedback.

**Comment by brauner** [comment]
Oh wow, sorry, I totally missed that issue. Hm, I think we should dumb this down and not log at warning or error level. This is not a fatal error and the fallback codepath is equally safe. When we use `TIOCGPTPEER` we're using a stashed fd to the container's `devpts` mount's `ptmx` device and allocating a new fd non-path based through this ioctl. If this ioctl can't be used we're falling back to allocating a pts device from the host's `devpts` mount's `ptmx` device which is path-based but is not under control of the container and so that's safe. The difference is just that the first method gets you a nice native terminal with all the pleasantries of having `tty` and friends working whereas the latter method does not.

**Comment by marcfiu** [comment]
Thanks for following up and fixing this.  What's the roadmap to see this
fix make it into 4.0.x stable release?

**Comment by brauner** [comment]
We're tagging a new release today.

**Comment by marcfiu** [comment]
Excellent.
