### ISSUE TITLE
ubuntu-cloud template image cache can get stale due to not saving release date

### ISSUE THREAD

**Issue by mikemccracken** [lxc/lxc#381]
## Summary

If you have an old image from the release you are requesting, e.g. Trusty from April, lxc-create using the ubuntu-cloud template will use that and not a more recent one.
## Details

in lxc-ubuntu-cloud.in, line 297 gets the url from ubuntu-cloudimg-query, e.g. 

```
ubuntu-cloudimage-query trusty released amd64 --format="%{url}\n"
```

This currently returns

```
https://cloud-images.ubuntu.com/server/releases/trusty/release-20141125/ubuntu-14.04-server-cloudimg-amd64.tar.gz
```

Note the `release-20141125`.

Then line 305 sets `filename` to the `basename` of that url, or just `ubuntu-14.04-server-cloudimg-amd64-root` (the ending gets munged in between, not important.)

Then `do_extract_rootfs()` downloads the image at that URL to a file named  `$cache/$filename`, leaving off the release identifier. 

If you look at http://cloud-images.ubuntu.com/releases/trusty/ , there are new releases often, with the same release name. If you created a trusty container in April, you're probably still using that image.

The template should save the release directory name along with the filename to ensure that you're getting the most recent image.
## Workaround

passing `-F` to the template flushes this cache and will result in a fresh image being downloaded, but it will of course force unnecessary downloads if your cached version is up to date.

**Comment by stgraber** [comment]
I'm not sure you always want to ditch the local copy since some of those are published daily, but having some kind of expiry like we do in the download template would indeed be useful

**Comment by battlemidget** [comment]
Hi, any eta on when this will be on the to-do list for an upcoming release?

**Comment by Kentoseth** [comment]
Hows about we set an expiry date for every 60 or every 90 days?

As Stephen suggested, it may not be a good idea to have the image being downloaded each time for making new containers, as this is a bandwidth hog.

You can also follow the format of updating a "base" container and using that as your main build (for other containers) with lxc-clone.

**Comment by Kentoseth** [comment]
On second-thought, I don't think having an expiry time will be such a good idea in practice.

Say for example you have a long-running container being used in production and haven't updated your image for 1 year, but your container itself gets auto-updates all the time.

Causing the image to expire by itself after a certain time (and no longer function) will be forcing a design-decision where upgrading the image may not always be possible.

Instead of forcing an expiry, a warning that specifies that the image is outdated would be a better option, so that it doesn't force anybody to update an image when they don't need/want to.

**Comment by brauner** [comment]
This should be fixed in the download template.
