### ISSUE TITLE
LXC 4.0 false claim: "Full cgroup2 support"

### ISSUE THREAD

**Issue by kc87** [lxc/lxc#3944]
Basic tools like lxc-ls, lxc-info etc. have no cgroup2 support at all! This is hardly "full support"!

**Comment by brauner** [comment]
LXC consists of a shared library `liblxc` and a set of binaries like `lxc-info`. The shared library can be compiled completely without the binaries and new announcements are always made about the shared library. Noteable changes to the binaries are separate mentioned usually.

The shared library has full cgroup2 support otherwise LXD would not work at all on such systems and so would other users of the shared library such as Proxmox. The binaries, as you correctly observed do not. This is mostly a matter of time. We can mention in this in the documentation in the future.
