### ISSUE TITLE
Support real restart from inside

### ISSUE THREAD

**Issue by jelmd** [lxc/lxc#4050]
# Required information
 * Distribution: Ubuntu
 * Distribution version: 20.04.3
 * The output of
   * `4.0.6`
   * `Linux kino5 5.4.0-81-generic #91-Ubuntu SMP Thu Jul 15 19:09:17 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

# Issue description

Right now an `init 6` or `reboot` inside a container does not really restart it (i.e. like `lxc-stop $container; sleep 1; lxc-start $container`), but the processes inside (i.e. init, etc.), only. We need a way to tell lxc, that it should reconfigure the container on the next reboot from inside. 

# Steps to reproduce
 1. echo '#!/bin/bash\nenv >/tmp/lxc.out\n' >/var/tmp/hook.sh
 2. chmod 0755 /var/tmp/hook.sh
 3. echo 'lxc.hook.start =  /var/tmp/hook.sh' >>$container/config
 4. ssh $container sudo reboot
 5. sleep 1
 6. ssh $container sudo reboot
 7. cat /tmp/lxc.out

No such file or directory because the hook never gets called.

The problem we are trying to solve is, that from time to time containers need to be reconfigured and thus a restart is required (e.g. because device were removed/added/modified). However, the admin who adjusts the container config (lxc operator) usually cannot restart the container immediately, because inside the container valuable compute processes are still running. Killing them is not an option. So the admin of the container (which has no access to the host of the container) should be able to trigger a container restart when it is appropriate.

**Comment by mihalicyn** [comment]
cc @stgraber

**Comment by stgraber** [comment]
The LXC monitor process which is spawned to handle the container doesn't now what configuration files were used, it only has the computed configuration. Given that liblxc clients (CLI tool or otherwise) can load any number of configuration files and perform alteration on the container config prior to starting it, having the container "reload" its config on reboot really isn't feasible.

What I'd recommend doing is what LXD and Incus do, use a `lxc.hook.stop` that detects if it's dealing with a stop or restart (look at `LXC_TARGET` in environment) and then based on that, either just exit 0 (for stop) or exit 1 (for restart) which will then prevent the container from restarting on its own and let your own logic start it back up by loading all the config.
