### ISSUE TITLE
lxc container journal mount problem

### ISSUE THREAD

**Issue by rfakit** [lxc/lxc#4106]
I have lxc contariner with the line at its own config (lxc_version : 4.0.6 )

lxc.mount.entry = /var/log/journal/56abd83f52ed4b53b6bd4c41f3564179 var/log/journal/56abd83f52ed4b53b6bd4c41f3564179 none bind,create=dir 0 0

but they are not synced. the directory in hosts is older than inside container and i create another line

lxc.mount.entry = /srv/log/machine1 var/log none bind,create=dir 0 0

it works perfectly fine for some container and doesnt work for the others.

what's the reason of that

**Comment by mihalicyn** [comment]
Hi @rfakit!

>but they are not synced.

I'm not sure that I understand this. What do you want to sync? Do you want to sync /var/log/journal between all the containers?

>the directory in hosts is older than inside container

can you clarify what this means? You are comparing a creation dates of these directories? Or are you comparing the modification time for directories contents?

As this issue is very-very old I'm closing it. Feel free to reopen if it's actual for you and you have questions.
