### ISSUE TITLE
lxc-attach init-uid calculation has regressed

### ISSUE THREAD

**Issue by hallyn** [lxc/lxc#4213]
# Issue description

Commit "c793e9f3bf: attach: move uid and gid handling to get_attach_context()" changed the calculation of the uid/gid to use.  Prior to that (for instance, in lxc-4.0.6) it looked at /proc/<pid of container init>/status for the uid it's running as.  So, if a container had

```
lxc.init.uid = 2000
```
Then lxc-attach would also use uid 2000.  Now, it will use the container's uid 0, unless you pass "-u 2000" to lxc-attach.

While obviously one can work around it by passing -u 2000 to lxc-attach. it *is* a regression / change in functionality which could confuse existing lxc based farms.

Do we want to re-establish the pre-existing behavior?

**Comment by mihalicyn** [comment]
cc @stgraber ?

**Comment by stgraber** [comment]
Yeah, I think it'd make sense to respect lxc.init.uid as we once did.

**Comment by hallyn** [comment]
Heh, sorry - as noone else commented on this, it obviously wasn't too much of a pain point for users, and as another 1.5 years has gone by, at this point I'd worry that changing this back now risks regressing users who expect the new behavior :)

So let's just look at it from a "which makes more sense" perspective.  IMO fixing the regression still makes more sense.  But whether we fix it or not, we should make sure to document it in the manpage (e.g. 

```
       -u, --uid uid
              Executes the command with user ID uid inside the container.  By default, use [the configured lxc.init.uid value. || 0]
```
)

Actually I suppose 0 might not even be mapped into the container, so lxc.init.uid is the sa[fn]er default.

**Comment by mihalicyn** [comment]
I have carefully analyzed this change and what was before and what we have now.

Let's look on this chunk of code (old code):
```
	if (options->namespaces & CLONE_NEWUSER) {
		/* Check whether nsuid 0 has a mapping. */
		ns_root_uid = get_ns_uid(0);

		/* Check whether nsgid 0 has a mapping. */
		ns_root_gid = get_ns_gid(0);

		/* If there's no mapping for nsuid 0 try to retrieve the nsuid
		 * init was started with.
		 */
		if (ns_root_uid == LXC_INVALID_UID)
			ns_root_uid = ctx->init_uid;

		if (ns_root_gid == LXC_INVALID_UID)
			ns_root_gid = ctx->init_gid;

		if (ns_root_uid == LXC_INVALID_UID)
			goto on_error;

		if (!lxc_switch_uid_gid(ns_root_uid, ns_root_gid))
```

So, intention was:
1. take UID 0 (inside the container's user namespace) and try to map it to the host UID
2. if mapping is valid => use this UID as a target UID
3. if mapping is NOT valid => take container's init process UID as a target.

But the problem is that the function `get_ns_uid` does the opposite thing! Instead of mapping namespace uid to the host, in fact, this function expects you to pass host's uid and map it *to* the user namespace. Just look:
```
	f = fopen("/proc/self/uid_map", "re");
	if (!f)
		return log_error_errno(0, errno, "Failed to open uid_map");

	while (getline(&line, &sz, f) != -1) {
		if (sscanf(line, "%u %u %u", &nsid, &hostid, &range) != 3)
			continue;

		if (hostid <= orig && hostid + range > orig)
			return nsid += orig - hostid;
```

And as this function was improperly used it was always failing which led to fallback path with using init processes's uid/gid values.

But when Christian reworked the algorithm, he consciously or not consciously fixed this bug. :-)

Please, correct me if I'm wrong.

**Comment by mihalicyn** [comment]
To conclude, original intention clearly was to use `0` by default and use init's process UID/GID as a fallback. But it never worked correctly.

**Comment by brauner** [comment]
Let's not reintroduce the old behavior after over a year. We don't do that in the kernel as well. Plus, it seems the old behavior never fully worked as @mihalicyn reported.
