### ISSUE TITLE
`lxc list` error message w.r.t. column `L` (Location of the instance) is inconsistent

### ISSUE THREAD

**Issue by m-ueberall** [lxc/lxc#4254]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 20.04 ("Focal"), 22.04 ("Jammy")
 * LXC/LXD: lxd v5.9-76c110d r24167 (Snap), v5.9-9879096 r24175 (Snap)

# Issue description / Steps to reproduce

In a _non-clustered_ environment, the output of `lxc list --columns […]L` and `lxc list --columns […]L[…]` is **inconsistent**:

```
[2023-01-09T21:49:25+0100] root@desktop01:/tmp# lxc list --columns ns46tSL pbuilder-amd64
+----------------+---------+----------------------+------+-----------+-----------+
|      NAME      |  STATE  |         IPV4         | IPV6 |   TYPE    | SNAPSHOTS |
+----------------+---------+----------------------+------+-----------+-----------+
| pbuilder-amd64 | RUNNING | 10.179.22.116 (eth0) |      | CONTAINER | 0         |
+----------------+---------+----------------------+------+-----------+-----------+
[2023-01-09T21:55:17+0100] root@desktop01:/tmp# lxc list --columns ns46tLS pbuilder-amd64
Error: Can't specify column L when not clustered
[2023-01-09T21:55:20+0100] root@desktop01:/tmp#
```

If column "`L`" is the last one selected, it is simply omitted; if it isn't the last one, this results in an error. (In a cluster, column "`L`" (`LOCATION`) would _always_ be shown next to column "`S`" using the above commands.)
This looks rather inconsistent--either the error should _always_ be returned in the absence of a cluster, or, better yet, column "`L`" should be _empty_ / `NULL` / `-` / `localhost` / _&lt;hostname&gt;_.

**EDIT:** If I choose fewer columns, the error is always displayed (so the inconsistency is dependent on the set of columns?):

```
[2023-01-09T21:55:20+0100] root@desktop01:/tmp# lxc list --columns nsL
Error: Can't specify column L when not clustered
[2023-01-09T22:12:26+0100] root@desktop01:/tmp# lxc list --columns nLs
Error: Can't specify column L when not clustered
```

**Comment by stgraber** [comment]
Yeah, that's normal and a bit of an edge case :)
`ns46tSL` is the default set of columns. When the CLI sees that set, it automatically strips `L` if not dealing with a cluster.

That's basically just an artifact of us having a default value set for `-c` as can be seen in `lxc list --help`.

We could have avoided that particular bit of weirdness by using a "magic" value instead. Say having the default column list set to `default` and then have the CLI select between `ns46tSL` or `ns46tS` based on whether clustering is on or off.
The issue with doing that is because the help message is generated by the CLI library we're using, it means that `lxc list --help` would show `(default "default")` rather than the more useful `(default "ns46tSL")` we're currently getting.

So all in all, we went with the current behavior as it felt like the better compromise :)
