### ISSUE TITLE
Error setting cgroup blkio

### ISSUE THREAD

**Issue by ivotron** [lxc/lxc#426]
On Ubuntu 12.04, kernel 3.13.0-44-generic, using lxc 1.0.7 (from lxc's ppa) I'm having trouble setting blkio settings on an SSD drive. I execute via docker (lxc-docker 1.4.1):

```bash
docker run -ti --rm=true \
  --lxc-conf=["lxc.cgroup.blkio.throttle.write_bps_device=8:60 31457280"] \
  -v /mnt/ssd:/mnt \
  stackbrew/ubuntu:trusty /bin/bash
```

And I get the following:

```
lxc-start: call to cgmanager_set_value_sync failed: invalid request
lxc-start: Error setting cgroup blkio:lxc/47934d15312f5686dace58819526923e6728c728b8ab596db5af2231
04867e5a limit type blkio.throttle.write_bps_device
lxc-start: failed to setup the cgroup limits for '47934d15312f5686dace58819526923e6728c728b8ab596d
b5af223104867e5a'
lxc-start: failed to spawn '47934d15312f5686dace58819526923e6728c728b8ab596db5af223104867e5a'
lxc-start: The container failed to start.
lxc-start: Additional information can be obtained by setting the --logfile and --logpriority optio
ns.
```

If I change from `8:60` to `8:48` which is a hdd device, container can be launched OK. Is there anyway I can pass `--logfile` or `--logpriority` to lxc-start via docker?

**Comment by stgraber** [comment]
So what device is 8:60?

My guess is that things are failing because either that device doesn't exist or it does exist but doesn't uses an I/O scheduler which is blkio aware.

In either case, that's not an LXC issue as the line is the right format, any failure is either a user/docker issue (not a valid device) or kernel issue (failing to apply the limit)
