### ISSUE TITLE
[man] Incorrect glyph for '-'

### ISSUE THREAD

**Issue by alejandro-colomar** [lxc/lxc#4361]
Hi,

In man(7) source, '\-' should be used for specifying an ASCII 0x2D, that
is, a hyphen-minus that can be pasted into terminals.  If the man(7)
source uses an unescaped '-', the output will be a UTF-8 hyphen, which
will not be understood by shells as part of a usual command line.  It
also makes it harder to search within the manual page.

In the lxc-create(1) manual page (and probably in all others of this project, but I didn't check), I see some hyphens are wrong.  Since
the page is autogenerated, the tool/script used to do that should be
fixed.

To reproduce it, open /etc/groff/man.local, and uncomment some code that
Debian maintainers have commented (it's commented out in Debian by
default, so that innocent manual page readers don't get affected by
bogus manual pages, at the expense of producing lower quality texts).

Here's what I see in my (tweaked) Debian Sid system:

```sh
alx@debian:~$ man lxc-create | sed -n '/SYNOPSIS/,/^$/p'
SYNOPSIS
       lxc-create {‐n name} [‐f config_file] {‐t template} [‐B backingstore] [‐‐
                  template‐options]

```
```sh
alx@debian:~$ man lxc-create | sed -n '/SYNOPSIS/,/^$/p' | hd
00000000  53 59 4e 4f 50 53 49 53  0a 20 20 20 20 20 20 20  |SYNOPSIS.       |
00000010  6c 78 63 2d 63 72 65 61  74 65 20 7b e2 80 90 6e  |lxc-create {...n|
00000020  20 6e 61 6d 65 7d 20 5b  e2 80 90 66 20 63 6f 6e  | name} [...f con|
00000030  66 69 67 5f 66 69 6c 65  5d 20 7b e2 80 90 74 20  |fig_file] {...t |
00000040  74 65 6d 70 6c 61 74 65  7d 20 5b e2 80 90 42 20  |template} [...B |
00000050  62 61 63 6b 69 6e 67 73  74 6f 72 65 5d 20 5b e2  |backingstore] [.|
00000060  80 90 e2 80 90 0a 20 20  20 20 20 20 20 20 20 20  |......          |
00000070  20 20 20 20 20 20 20 20  74 65 6d 70 6c 61 74 65  |        template|
00000080  e2 80 90 6f 70 74 69 6f  6e 73 5d 0a 0a           |...options]..|
0000008d
```

(I reported this to the mailing list, but I don't see it in the archives, so I guess the list is subscribers-only.)

Cheers,
Alex

**Comment by stgraber** [comment]
Seems to be considered as a docbook2man bug: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=208967

The problem is that there are a dozen different projects that can handle converting docbook sgml to manpages and not all of them behave in the same way. Trying to trick Debian's docbook2man into doing the right thing by altering the source sgml would likely result in nasty rendering in other distros.

For Debian and Ubuntu, it looks like the docbook2man bug has been largely ignored for the past decade, instead dealing with that problem by using that groff config you pointed out earlier.

**Comment by stgraber** [comment]
Similar report for docbook2x here: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=631078
