### ISSUE TITLE
http://images.linuxcontainers.org/ down?

### ISSUE THREAD

**Issue by bikb** [lxc/lxc#4407]
Hello,

I cannot reach https://images.linuxcontainers.org/ or http://images.linuxcontainers.org/.

Is this connection used by lxc-create?

I tried 2 different providers.

Please can you help?

Best regards

**Comment by stgraber** [comment]
The solution we use to manage DNSSEC hit a bug last night and incorrectly detected the new DNSSEC KSK keys as having been published when they in fact were not.

This caused DNSSEC validating servers to progressively fail to validate our DNS zones...

To make things more annoying, the external monitoring solution that's used to check availability of all our services does not appear to be validating DNSSEC records, meaning that as far as monitoring was concerned, all services were properly up and running and everything was fine.

What eventually caught the issue was another layer of monitoring flagging an excess of DNS queries to our DNS servers, that was caused by all the DNSSEC validating resolvers re-trying their queries. As soon as that alert triggered, we manually updated all the public KSK records to line up with OpenDNSSEC's expected ones and we saw traffic return to normal level since.
