### ISSUE TITLE
Capability CAP_NET_ADMIN not dropped when using shared NET namespace.

### ISSUE THREAD

**Issue by r10r** [lxc/lxc#678]
Hi,

i recognized that 

 `lxc.cap.drop = net_admin`

is not enforced when the container is started with a shared network namespace:

`lxc-start -n debian.sid-1 --share-net=15692 -d`

when attaching to the container with:

`lxc-attach -s "MOUNT|PID|UTSNAME|IPC|NETWORK" -n debian.sid-1`

I can modify the network configuration with `ip` or `ifconfig` which should not be possible.
Is this indented behaviour? How can I drop CAP_NET_ADMIN for a shared NET namespace?

Regards,
Ruben

```
root@enz:~# lxc-info --version
1.0.7
root@enz:~# uname -a
Linux enz 4.0.0-2-amd64 #1 SMP Debian 4.0.5-1 (2015-06-16) x86_64 GNU/Linux
```

**Comment by hallyn** [comment]
(I'm curious how many people use --share-net;  doesn't work for me)

can you show what /proc/self/status and /proc/1/status show during that lxc-attach?  I'm wondering whether CAP_NET_ADMIN actually shows up in the bounding set.

**Comment by hallyn** [comment]
Please show the full configuration for both containers.

**Comment by hallyn** [comment]
Thanks for reporting this.

I actually cannot get share-net to work at all - it always seems
to hang the caller.

I don't disbelieve your findings :) but they don't quite make sense.
The lxc.net.drop is done regardless of share-net, so it should apply
regardless of your user namespace.  Very curious.  But as I say,
I can't even get it to work at all right now so I guess i should
start there.

**Comment by hallyn** [comment]
Note that if the first container unshared a user ns and the second
did not, then this would be expected and out of the hands of lxc.

**Comment by hallyn** [comment]
After playing around a bit,

my initial failures were due to not removing the network entries.  This
caused lxc to segv during setup_network().  Probably worth a separate bug.

When I start a2 --share-net a1, if I then 

lxc-attach -n a2

my network namespace is not attached to a1's.  This is because CLONE_NEWNET
is not in the listed clone_flags.  This is probably the core of this bug.
Because of this, you are still in the initial network namespace, not the
container's.

If I then do

lxc-attach -n a2 -s 'MOUNT|NETWORK|PID'

this attaches me to a1's network, but because -s implies -e I have elevated
privileges.  So while pid 1 (you can see by /proc/1/status) has dropped
capabilities, my attached process does not.

Could this be what's happening with you?  So your container itself does not
have privilege over the network, but the attached processes do.

How exactly did you attach?

**Comment by r10r** [comment]
Hi Serge,

this is exactly what is happening to me.
I always attach with `-s "MOUNT|PID|UTSNAME|IPC|NETWORK"` because the 
process should be attached to the shared network namespace of the container.
But as you described the attached process then runs with elevated privileges so `CAP_NET_ADMIN` is not dropped.

How can we fix this?

Regards
Ruben

**Comment by hallyn** [comment]
On Tue, Jan 12, 2016 at 03:15:24AM -0800, Ruben Jenster wrote:
> Hi Serge,
> 
> this is exactly what is happening to me.
> I always attach with `-s "MOUNT|PID|UTSNAME|IPC|NETWORK"` because the 
> process should be attached to the shared network namespace of the container.
> But as you described the attached process then runs with elevated privileges so `CAP_NET_ADMIN` is not dropped.
> 
> How can we fix this?

We need to separate the handler->clone_flags from the handler->ns_flags (or somesuch).
The one would be the flags to be flags passed to clone(), the other the flags used
everywhere else to show which namespaces the container actually has separate from
host.

In terms of minimizing the patch, just having lxc_spawn pass preserve_mask to
lxc_clone() and having lxc_clone use handler->clone_flags & preserve_mask may
work and would be simplest.

**Comment by brauner** [comment]
I've reworked the namespace sharing logic in both start and attach substantially so this should not be an issue anymore. If it still is, please re-open.
