### ISSUE TITLE
Failed to mount cgroup at /sys/fs/cgroup/systemd: Permission denied

### ISSUE THREAD

**Issue by srkunze** [lxc/lxc#685]
What am I missing here? Using Ubuntu 14.04.

`lxc-test` is a Ubuntu 15.10 container.

```
root@host:~# lxc-ls -f
NAME      STATE    IPV4  IPV6  AUTOSTART  
----------------------------------------
lxc-test  STOPPED  -     -     NO         
root@host:~# lxc-start -n lxc-test 
Failed to mount cgroup at /sys/fs/cgroup/systemd: Permission denied
systemd 225 running in system mode. (+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ -LZ4 +SECCOMP +BLKID -ELFUTILS +KMOD -IDN)
Detected virtualization lxc.
Detected architecture x86-64.

Welcome to Ubuntu 15.10!

Set hostname to <lxc-test>.
Failed to install release agent, ignoring: No such file or directory
Failed to create root cgroup hierarchy: No such file or directory
Failed to allocate manager object: No such file or directory
[!!!!!!] Failed to allocate manager object, freezing.
```

**Comment by stgraber** [comment]
Ubuntu 14.04 has LXC 1.0.7 which doesn't support running systemd inside the container.

You can install the LXC 1.1.4 backport available in trusty-backports which should fix that (enabled backports in /etc/apt/sources.list, then apt-get update, then apt-get -t trusty-backports install lxc) or use the stable LXC PPA at ppa:ubuntu-lxc/stable

Anyway, not a bug, that's why we release LXC 1.1 :)

**Comment by srkunze** [comment]
Alright. Thanks for the very quick response. Let me see if I can get this running.

**Comment by srkunze** [comment]
@stgraber Can I use the container created with lxc 1.0.7?

**Comment by stgraber** [comment]
Yeah, it should be fine. LXC shouldn't have changed anything inside the generated rootfs.

**Comment by dann1** [comment]
hello I had the same problem and I installed lxc 1.1.5, then the containers fail to start again but the terminal says somthing else: "lxc-start: lxc_start.cc: main: 344 The container failed to start" , I've used containers with no problem on debian 8.2 but I'm trying to run them on ubuntu 14.04, after an apparently successful lxc-create I try to start it using lxc-start -n name but terminal shows the previous error

**Comment by hallyn** [comment]
When reporting failures, please show the output of

lxc-start -n <container> -F -l trace -o /dev/stdout

and the package versions for lxc, cgmanager, and lxcfs.

**Comment by mdone-cloudian** [comment]
I'm having exactly this on a CentOS 7.6 host running containers also with CentSO 7.6. The host was setup by a colleague, our internal documentation directs him to install `snapd` then `snap install lxd`. I'm not sure what else he might have done, sorry. LXD/LXC version is 3.19.

It would be nice to know the root cause of this, or the PR that fixed it, or the bug related to it.

More about the setup as far as I can see:`lxc-checkconfig` is all green, but `namespace.unpriv_enable=1` is not in `/proc/cmdline`. We're running `lxc` as root (hosts are semi volatile QA VMs) so no unix socket perms errors. Config looks minimal and similar to other hosts where this is working fine:

```yaml
config:
  cluster.https_address: 10.50.110.91:8443
  core.https_address: 10.50.110.91:8443
  core.trust_password: true
```

As I mentioned, this same config and image is running fine in other similar hosts. What should I do to start debugging this thing?
