### ISSUE TITLE
Verify that container is not privileged

### ISSUE THREAD

**Issue by srkunze** [lxc/lxc#687]
As described here https://linuxcontainers.org/lxc/getting-started/#creating-unprivileged-containers-as-root

How can I verify that the container runs without privileges?

The `/etc/subuid` and `/etc/subgid` looks like this:
```
root@host:~# cat /etc/subuid
test:100000:65536
root:100000:65536
root@host:~# cat /etc/subgid
test:100000:65536
root:100000:65536
```

That's the output of `ps aux --forest`:
```
root      3198  0.0  0.0  43228  1612 ?        Ss   23:02   0:00          \_ [lxc monitor] /var/lib/lxc lxc-test
root      3213  0.0  0.0  36460  1960 ?        Ss   23:02   0:00          |   \_ /sbin/init
```

**Comment by stgraber** [comment]
That is a privileged container.

Unless you changed /etc/lxc/default.conf or are running the lxc commands as your own user, the containers are going to be privileged by default. That's intentional to prevent regression for existing users.

To create unprivileged containers, you need to setup a uid/gid map in /etc/subuid and /etc/subgid, then put the matching config either in ~/.config/lxc/default.conf if creating containers from your own user or in /etc/lxc/default.conf if creating containers as root.

Existing containers can't trivially be converted to unprivileged using the LXC tools, so your best bet is to re-create them.


Note that a lot of that complexity is why we started the LXD project which does use unprivileged containers by default and makes configuring such things as easy as possible.

**Comment by srkunze** [comment]
Alright. Thanks.

> To create unprivileged containers, you need to setup a uid/gid map in /etc/subuid and /etc/subgid, then put the matching config either in [...]

What is the reason to duplicate this?

> Existing containers can't trivially be converted to unprivileged using the LXC tools, so your best bet is to re-create them.

I thought so and re-created it (btw. after upgrading lxc to 1.1.4, Wily is missing from the download template -- I used it anyway and it work from the cache)

> Note that a lot of that complexity is why we started the LXD project which does use unprivileged containers by default and makes configuring such things as easy as possible.

I see. I just thought I could start by the basics and setting up some containers to see how it fares.

**Comment by srkunze** [comment]
`ps aux --forest` again
```
root      4232  0.0  0.0  43228  1624 ?        Ss   23:25   0:00          \_ [lxc monitor] /var/lib/lxc lxc-test
100000    4249  0.0  0.0  36460  1956 ?        Ss   23:25   0:00              \_ /sbin/init
```

**Comment by hallyn** [comment]
>>     To create unprivileged containers, you need to setup a uid/gid map in
>>     /etc/subuid and /etc/subgid, then put the matching config either in [...]

> What is the reason to duplicate this?

The /etc/subuid and /etc/subgid files are owned by the host admin and
officially delegate the subuids to the user, for whatever they want.

The lxc config files specify mappings to user for a particular container.
You could for instance split your mapping up so as to separate the uid
ranges for different containers.  You might want to allocate one range
to container uids 0-1050;  one id (your host userid) to some uid, say
200000, in the container, and one id to 65535 in the container to make
sure there was a nobody.

**Comment by srkunze** [comment]
@hallyn Okay, sounds reasonable. It's just hard to get it right at the first time. I've to admit that I've never heard of subuids before lxc.

**Comment by hallyn** [comment]
On Wed, Nov 04, 2015 at 12:10:23PM -0800, Sven R. Kunze wrote:
> @hallyn Okay, sounds reasonable. It's just hard to get it right at the first time. I've to admit that I've never heard of subuids before lxc.

yeah, it's a new concept, but not lxc-specific.  Not using them is not a good option, but abstracting the complications away is.  We're hoping to make it much easier very soon.
