### ISSUE TITLE
lxc-destroy destroys a wrong container (bug in lxc-clone)

### ISSUE THREAD

**Issue by tchwpkgorg** [lxc/lxc#694]
lxc-destroy will destroy a wrong container if lxc-clone -B dir was interrupted (ctrl+c).

Mailing list report with a way to reproduce: https://lists.linuxcontainers.org/pipermail/lxc-users/2015-November/010419.html

**Comment by brauner** [comment]
For completeness sake:
The cause is the incomplete clone: When you clone a container config of the
original container gets copied. After the clone (copying the storage etc.)
succeeds the config is updated. That means before the config is updated the
config of your clone still contains the rootfs path to the original container.
You can verify this by doing:

        # lxc-clone -B dir testvm012d testvm13d
        [ctrl+c]

and checking

        YOUR-FAVOURITE editor testvm13d/config

it should still contain

        lxc.rootfs = /path/to/testvm012d/rootfs

in contrast to when the copy of the rootfs of the original container succeeds.
Then it will contain:

        lxc.rootfs = /path/to/testvm13d/rootfs

**Comment by hallyn** [comment]
At one point this was handled right.  It regressed when the unexpanded_config was introduced, because the rootfs was cleared (temporarily) in the old container's lxc_conf, not in its unexpanded config.
