### ISSUE TITLE
Improve error handling

### ISSUE THREAD

**Issue by brauner** [lxc/lxc#723]
Improve error handling in lxc

As we have discussed in a few mails error handling in lxc should be improved.
Here are two different suggestions.

We should start by defining a set of reusable error codes which are modelled
after traditional C error codes. They should be put in a common header
`lxc_error.h`. An example could be:

```
    #define ELXCIDMAP 1 /* Indicates missing or invalid id mapping. /*
```

Associated with it we can have a really small set of error handling functions.
Something in the spirit of `strerror()` e.g. `lxc_strerror()` which turns the error
code into a human readable string that gives useful information about the error.

This should be the smallest common denominator for an error checking system. From
this point onward I see two possible ways to proceed.

(1) Simple and fast error handling:

We keep an `error_num` variable in `struct lxc_container *current_config` which
contains the last error code which we can report back to the user.

`error_num` will only be set by the api functions defined in lxccontainer.c.

(2) Sophisticated error handling:

The more full-blown approach would probably be to define error codes per module.
That means we would have a simple `struct lxc_error` in `struct lxc_container
*current_config` with a field for a module and an associated error code. A module
here would be e.g. bdev.h. `lxc_strerror()` would then take two arguments: module
and error code and return an appropriate human readable string.

Icing:

When this is working we can discuss if we want to add a `struct lxc_list
*error_list` that is a list of strings or error codes of all the things that went
wrong. (In the spirit of what @hallyn suggested.)

**Comment by hallyn** [comment]
Both of those might be fine, but let me complicate it with another proposal :) Feel free to shoot down:

1. Classify our error messages into two types: leaf and non-leaf.

2. Keep a variable-sized lxc_conf->error_msg

3. when we get a non-leaf error message, for instance we just called
   open_file(), which returned a failure, we do (pseudo-code)

   	current_config->error_msg = "%s: %s" % (our_new_message, current_config->error_msg)

2. When we get a leaf error message (like, inability to open a file), we
   a. call lxc_error_dump() which prints out current_config->error_msg
   b. set current_config->error_msg to just our new error message.

3. lxc_error_dump() would nicely format the message so that each set of related messages is clearly related.

**Comment by AustinReichert** [comment]
Here's the PR for the progress I've made on this, I would appreciate feedback :) https://github.com/lxc/lxc/pull/1997

**Comment by brauner** [comment]
Our error handlig has been improved substantially and I still intend to rip out some of the stuff @AustinReichert did and integrate some of it into liblxc.
