### ISSUE TITLE
First run of lxc command outputs incorrect/misleading information

### ISSUE THREAD

**Issue by petermatulis** [lxc/lxc#763]
The first time command *lxc* is run the following text is output:

    If this is your first run, you will need to import images using the 'lxd-images' script.
    For example: 'lxd-images import ubuntu --alias ubuntu'.

This is not necessarily true. You can alternatively use a remote to access images:

    lxc remote add remote images.linuxcontainers.org
    lxc launch remote:ubuntu/trusty/i386 ubuntu-test

**Comment by stgraber** [comment]
This issue should be filed against lxd, not lxc :)

I agree that the instructions aren't accurate, however they do match our recommendation as far as images. Images coming from lxd-images are supported, official distribution images, images.linuxcontainers.org are automatically generated, community images which don't get any automated testing, which is why we're not recommending them as a default.

Note that all of this will be changing once we get direct simplestream support in lxd, at which point we expect things to simply look like "lxc launch ubuntu:trusty ubuntu-test"
