### ISSUE TITLE
/etc/cron.hourly/lxd has incorrect text or /etc/default/lxd is missing

### ISSUE THREAD

**Issue by petermatulis** [lxc/lxc#764]
On Ubuntu 15.10 I have the lxd and lxc packages installed:

lxc     1.1.5-0ubuntu3~ubuntu15.10.1~ppa1
lxd     0.26-0ubuntu3~ubuntu15.10.1~ppa1

File */etc/cron.hourly/lxd* contains:

    #!/bin/sh -eu

    # This cronjob will update any image in the local LXD image store which
    # was imported with the --sync flag set.
    #
    # As LXD is socket activated on systemd, this cron job will only trigger
    # if LXD is already running or if FORCE_IMAGE_SYNC is set to true in
    # /etc/default/lxd

    FORCE_IMAGE_SYNC="false"

    [ -e /etc/default/lxd ] && . /etc/default/lxd

    if type systemctl >/dev/null 2>&1 && ! systemctl -q is-active lxd; then
        [ "${FORCE_IMAGE_SYNC}" != "true" ] && exit 0
    fi

    exec lxd-images --quiet sync

 1. It mentions */etc/default/lxd* but this file does not exist on my system.
 1. It also uses FORCE_IMAGE_SYNC which seems to belong in */etc/default/lxd*.

**Comment by stgraber** [comment]
Hi,

This should have been filed against the lxd repository, not lxc :)

Anyway, what you're seeing isn't a bug at all.

We have a default of only importing images if lxd is running, this behavior can be overriden through an environment variable (defaults to false) and you can set such an environment variable in /etc/default/lxd.

The file may not exist on your system and that's fine, that's why we're only sourcing it if it does exist.
