### ISSUE TITLE
Bad relative mount path

### ISSUE THREAD

**Issue by sidnei** [lxc/lxc#78]
Seems like mount.entry with a relative path has been broken recently. Juju creates an lxc config with an entry like:

```
lxc.mount.entry = /home/user/.juju/env/log var/log/juju
```

However, using latest lxc from the ppa it tries to mount that into:

```
/usr/lib/x86_64-linux-gnu/lxc/var/log/juju
```

... instead of relative to rootfs. As such, the container fails to start.

Incidentally, during lxc-create the logs also seem to use that same path. Seems like some option is not being passed around correctly.

```
lxc-create 1382535470.641 DEBUG    bdev - trying to mount '/dev/lxc/precise-best'->'/usr/lib/x86_64-linux-gnu/lxc' with fstype 'ext3'
lxc-create 1382535470.760 INFO     bdev - mounted '/dev/lxc/precise-best' on '/usr/lib/x86_64-linux-gnu/lxc', with fstype 'ext3'
```

**Comment by drydenp** [comment]
What confuses people is just that thing mount error (probably) references the "pivot mount point" that is temporarily used and then exchanged for the real mount point (the thing people have configured). In my case I had just specified a bind mount wrong (in fstab format) and the error was only that 'bind' as a type did not exist ;-). But the error was very cryptic for me until I realized (as per this thread, for me) that it had nothing to do with paths. So the issue is more that the error message is cryptic than anything else.

This was on Debian 8 with LXC 1.0.6 so I cannot say about 2.0.5 at this point but I guess the issue could still be relevant here. Regards.

**Comment by baszoetekouw** [comment]
Note that this is _still_ an issue (lxc 3.0.2 in Ubuntu 18.10): the error message is quite cryptic and suggests that mounting is happening in the worng dir (an ordinary user like myself is probably not aware how mounting is handled behind the screen, and that "pivot mount points" in /usr/lib are involved at al).  

A simple check to see if the dir/file to be mounted exists, before trying to actually mount it, would probably solve this quite effectively.
