### ISSUE TITLE
kernel.shm* settings to work in lxc containers

### ISSUE THREAD

**Issue by matt4d617474** [lxc/lxc#989]
Per https://github.com/lxc/lxd/issues/1351, stgraber mentioned that LXC should allow a rw bindmount to these /proc/sys/kernel/shm\* tunables.  At present, writing to them yields a read-only fs error message.

Alternatively, if the physical host setting would be passed down (for shmmax; it's not currently), that would also ease a lot of my troubles with older PostgreSQL installations.

Thanks much!

Matt

**Comment by brauner** [comment]
LXC master has support for all `/proc/sys` kernel tunables through:

```
lxc.sysctl.[kernel parameters name]
              Specify  the kernel parameters to be set. The parameters available are those listed under /proc/sys/.  Note that not all sysctls are
              namespaced. Changing Non-namespaced sysctls will cause the system-wide setting to be modified.  sysctl(8).  If used with  no  value,
              lxc will clear the parameters specified up to this point.
```

So this can be closed.

**Comment by johaven** [comment]
Is it implemented since lxc 3.0 ?
```
vm 100 - unable to parse config: lxc.sysctl.kernel.shmmax: 17179869184
```

**Comment by brauner** [comment]
Are you using LXD or LXC if LXD, please show:
```
lxc info
```
and the container's config.

**Comment by brauner** [comment]
@Blub?

**Comment by okuryan** [comment]
@Blub , we do not see any patch and no related commits? And bug is marked as resolved and this issue is also marked as closed. Where is patch?

**Comment by okuryan** [comment]
@Blub , just to clarify, I'm using PROXMOXX with LXC. I have a VM and I manually add in file /var/lib/lxc/109/config the following parameter:

`lxc.sysctl.kernel.shmmax = 17179869184`

But after VM restart - this parameter disappears automatically!

**Comment by lhorace** [comment]
Hello there,

That can be explained easily, don't place the config there! That location is volatile, for persistence, It should be written to /etc/pve/lxc/109.conf!

Regards

**Comment by johaven** [comment]
If i put _lxc.sysctl.kernel.shmmax = 17179869184_ in my 105.conf file, the container failed to start.

This is not working and i got the last proxmox update (Linux pvx-center 4.15.18-14-pve #1 SMP PVE 4.15.18-39)

**Comment by lhorace** [comment]
Report the issue on the PVE forums? I have proxmox 5.3 but IIRC, the latest one is 5.5-6 or 5.6. Not to sure. Looking at the bug report, the patch is somewhere on the dev ml, I would have to search for it. And if I reading the report correctly, the affected component is pve-common.

Regards

**Comment by lhorace** [comment]
Also:

> There's a patch on the list for this now. Note that the lxc.sysctl.* keys require write access to /proc/sys so they only work with `lxc.mount.auto: proc:rw`.

From my understanding, for _lxc.sysctl.kernel.shmmax_ to work, you need to include the above.

Cheers

**Comment by okuryan** [comment]
@lhorace , but doing `lxc.mount.auto: proc:rw ` will make global kernel config editable from individual VM
That means modification of kernel configs that anybody can do on one individual VM can break the whole virtualization system and all our 50+ servers will just stop working.

So that recommendation doesn't make sense at all. 

We just need this configs to be applied on individual VM without affecting other VMs
Does LXC virtualization even supports this?

**Comment by lhorace** [comment]
@okuryan 

>  individual VM

You mean containers?

> We just need this configs to be applied on individual VM without affecting other VMs
Does LXC virtualization even supports this?

Again, you mean containers right? LXC is not virtualization technology but a containment technology. IDK, isn't /proc namespace ? Besides, this issue and proxmox bug report is about enabling support for _lxc.sysctl.*_. If that's not what you want, perhaps you should open a new issue? You can also raise the issue on the Forums or on the proxmox bug report? Lastly, what happens if you don't put _lxc.mount.auto: proc:rw_ but still include you _lxc.sysctl.*_ settings, what happens then? If you up2date and still having problems starting the container, then raise a bug report at http://bugzilla.proxmox.com/ ?

**Comment by okuryan** [comment]
@lhorace , thanks for response. 
Yes, when I'm saying VM, I refer to container. Sorry for my terminology, I'm not so experienced in this things

> Lastly, what happens if you don't put lxc.mount.auto: proc:rw but still include you lxc.sysctl.* settings, what happens then?

And to answer your question, if not putting proc:rw option and put lxc.sysctl.* setting, container will just fail to start, because it cannot set this option as sysctl configs are readonly. And that doesn't make sense to me, as why I want to make it rw, just to put predefined configs? Anyway I do not want users to manually edit kernel options inside container themselves.
So you re saying this is proxmox bug? If yes than I will immediately submit it to proxmox team.

**Comment by okuryan** [comment]
@lhorace one more point. As I know , LXC is shared kernel solution. So maybe what I'm saying doesn't make sense at all, because all those sysctl options are global and applied to host machine always? Just because LXC works like this? Maybe I just need to switch to KVM and that is it?

**Comment by lhorace** [comment]
> And to answer your question, if not putting proc:rw option and put lxc.sysctl.* setting

I like to clarify two things here:

1. With `proc:rw`, only the container itself is affected
2. Isn't `root` required inside the container to make those changes?

> So maybe what I'm saying doesn't make sense at all, because all those sysctl options are global and applied to host machine always?

My understanding is `/proc` is namespace'd, developers could opt in and clarify this if my assumption is incorrect. So only the container itself should be affected by changes in `/proc`. http://man7.org/linux/man-pages/man7/pid_namespaces.7.html didn't shed any light on this.

> container will just fail to start, because it cannot set this option as sysctl configs are readonly
> So you re saying this is proxmox bug? If yes than I will immediately submit it to proxmox team.

Reviewing what you posted, seems like a limitation be it the Kernel or LXC. In this case, is unrelated to this issue, perhaps you should open a new issue describing the problem with LXC developers? A bug report with proxmox with link issue on github could help sort all this out for you.

**Comment by joydashy** [comment]
I actually tried this on Proxmox to get Gitlab to work within LXC:
> lxc.mount.auto: proc:rw
> lxc.sysctl.kernel.sem = 250 32000 32 262
> lxc.sysctl.kernel.shmall = 4194304
> lxc.sysctl.kernel.shmmax = 17179869184
> lxc.sysctl.net.core.somaxconn = 1024

After booting this container, things on the host actually changed, specifically, the overview of containers within Proxmox was no longer working correctly. When the container is shutdown, the problem is immediately resolved. So it appears this is not a safe way to go about this problem. Anyone have a better solution?
